"""Mobile category skeleton v2 — generated from aivai_mobile Dart data.

Regenerate:
    python -m scripts.generate_mobile_category_skeleton
"""
from __future__ import annotations

from app.models.category_enums import CategoryEntityType

# (parent_slug, slug, name, entity_type_name, sort_order)
# parent_slug is backend root slug (L2) or mobile v2 L2 slug (L3).
MOBILE_CATEGORY_SKELETON: list[tuple[str, str, str, str, int]] = [
    ("transport", "transport-car-sale", "Продажа авто", CategoryEntityType.object, 10),
    ("transport", "transport-auto-parts", "Автозапчасти", CategoryEntityType.object, 20),
    ("transport", "transport-accessories-tuning", "Аксессуары и тюнинг", CategoryEntityType.object, 30),
    ("transport", "transport-tires-wheels", "Шины и диски", CategoryEntityType.object, 40),
    ("transport", "transport-auto-services", "Автоуслуги", CategoryEntityType.object, 50),
    ("transport", "transport-moto-tech", "Мототехника", CategoryEntityType.object, 60),
    ("transport", "transport-electric", "Электротранспорт", CategoryEntityType.object, 70),
    ("transport", "transport-commercial", "Коммерческий транспорт", CategoryEntityType.object, 80),
    ("transport", "transport-bicycles", "Велосипеды", CategoryEntityType.object, 90),
    ("transport", "transport-special-equipment", "Спецтехника", CategoryEntityType.object, 100),
    ("transport", "transport-cargo", "Грузовой транспорт", CategoryEntityType.object, 110),
    ("transport", "transport-watercraft", "Водный транспорт", CategoryEntityType.object, 120),
    ("transport", "transport-trailers", "Прицепы и полуприцепы", CategoryEntityType.object, 130),
    ("transport", "transport-farm-machinery", "Сельхозтехника", CategoryEntityType.object, 140),
    ("transport", "transport-rental", "Аренда транспорта", CategoryEntityType.object, 150),
    ("transport", "transport-buyback-exchange", "Скупка/обмен транспорта", CategoryEntityType.object, 160),
    ("transport-auto-parts", "transport-auto-parts-dvigatel-i-navesnoe", "Двигатель и навесное", CategoryEntityType.object, 10),
    ("transport-auto-parts", "transport-auto-parts-korobka-peredach-i-transmissiya", "Коробка передач и трансмиссия", CategoryEntityType.object, 20),
    ("transport-auto-parts", "transport-auto-parts-hodovaya-i-podveska", "Ходовая и подвеска", CategoryEntityType.object, 30),
    ("transport-auto-parts", "transport-auto-parts-rulevoe-upravlenie", "Рулевое управление", CategoryEntityType.object, 40),
    ("transport-auto-parts", "transport-auto-parts-tormoznaya-sistema", "Тормозная система", CategoryEntityType.object, 50),
    ("transport-auto-parts", "transport-auto-parts-kuzovnye-detali", "Кузовные детали", CategoryEntityType.object, 60),
    ("transport-auto-parts", "transport-auto-parts-kabina-perednyaya-chast-nouskat", "Кабина / передняя часть / ноускат", CategoryEntityType.object, 70),
    ("transport-auto-parts", "transport-auto-parts-bampery-i-komplektuyuschie", "Бамперы и комплектующие", CategoryEntityType.object, 80),
    ("transport-auto-parts", "transport-auto-parts-dveri-i-komplektuyuschie", "Двери и комплектующие", CategoryEntityType.object, 90),
    ("transport-auto-parts", "transport-auto-parts-kapoty-i-kryshki-bagazhnika", "Капоты и крышки багажника", CategoryEntityType.object, 100),
    ("transport-auto-parts", "transport-auto-parts-zerkala-i-komplektuyuschie", "Зеркала и комплектующие", CategoryEntityType.object, 110),
    ("transport-auto-parts", "transport-auto-parts-stekla-i-komplektuyuschie", "Стёкла и комплектующие", CategoryEntityType.object, 120),
    ("transport-auto-parts", "transport-auto-parts-optika-fary-i-fonari", "Оптика, фары и фонари", CategoryEntityType.object, 130),
    ("transport-auto-parts", "transport-auto-parts-reshetki-zhabo-i-naruzhnyy-plastik", "Решётки, жабо и наружный пластик", CategoryEntityType.object, 140),
    ("transport-auto-parts", "transport-auto-parts-krylya-i-podkrylki", "Крылья и подкрылки", CategoryEntityType.object, 150),
    ("transport-auto-parts", "transport-auto-parts-bryzgoviki-i-zaschita-dnischa", "Брызговики и защита днища", CategoryEntityType.object, 160),
    ("transport-auto-parts", "transport-auto-parts-silovye-elementy-kuzova", "Силовые элементы кузова", CategoryEntityType.object, 170),
    ("transport-auto-parts", "transport-auto-parts-salon-i-interer", "Салон и интерьер", CategoryEntityType.object, 180),
    ("transport-auto-parts", "transport-auto-parts-elektrika-i-elektronika", "Электрика и электроника", CategoryEntityType.object, 190),
    ("transport-auto-parts", "transport-auto-parts-klimat-pechka-i-konditsioner", "Климат, печка и кондиционер", CategoryEntityType.object, 200),
    ("transport-auto-parts", "transport-auto-parts-sistema-ohlazhdeniya", "Система охлаждения", CategoryEntityType.object, 210),
    ("transport-auto-parts", "transport-auto-parts-toplivnaya-sistema", "Топливная система", CategoryEntityType.object, 220),
    ("transport-auto-parts", "transport-auto-parts-vyhlopnaya-sistema", "Выхлопная система", CategoryEntityType.object, 230),
    ("transport-auto-parts", "transport-auto-parts-podshipniki", "Подшипники", CategoryEntityType.object, 240),
    ("transport-auto-parts", "transport-auto-parts-krepezh-rezinki-i-melkie-detali", "Крепёж, резинки и мелкие детали", CategoryEntityType.object, 250),
    ("transport-auto-parts", "transport-auto-parts-masla-zhidkosti-i-rashodniki", "Масла, жидкости и расходники", CategoryEntityType.object, 260),
    ("transport-auto-parts", "transport-auto-parts-universalnye-detali", "Универсальные детали", CategoryEntityType.object, 270),
    ("transport-auto-parts", "transport-auto-parts-drugoe", "Другое", CategoryEntityType.object, 280),
    ("transport-accessories-tuning", "transport-accessories-tuning-avtozvuk-i-multimediya", "Автозвук и мультимедия", CategoryEntityType.object, 10),
    ("transport-accessories-tuning", "transport-accessories-tuning-avtosvet-i-tyuning-optiki", "Автосвет и тюнинг оптики", CategoryEntityType.object, 20),
    ("transport-accessories-tuning", "transport-accessories-tuning-elektronika-i-bezopasnost", "Электроника и безопасность", CategoryEntityType.object, 30),
    ("transport-accessories-tuning", "transport-accessories-tuning-aksessuary-salona", "Аксессуары салона", CategoryEntityType.object, 40),
    ("transport-accessories-tuning", "transport-accessories-tuning-aksessuary-kuzova", "Аксессуары кузова", CategoryEntityType.object, 50),
    ("transport-accessories-tuning", "transport-accessories-tuning-bagazhniki-i-perevozka", "Багажники и перевозка", CategoryEntityType.object, 60),
    ("transport-accessories-tuning", "transport-accessories-tuning-vnedorozhnyy-tyuning", "Внедорожный тюнинг", CategoryEntityType.object, 70),
    ("transport-accessories-tuning", "transport-accessories-tuning-sportivnyy-tyuning", "Спортивный тюнинг", CategoryEntityType.object, 80),
    ("transport-accessories-tuning", "transport-accessories-tuning-instrumenty-i-avtoaksessuary", "Инструменты и автоаксессуары", CategoryEntityType.object, 90),
    ("transport-accessories-tuning", "transport-accessories-tuning-drugoe", "Другое", CategoryEntityType.object, 100),
    ("transport-tires-wheels", "transport-tires-wheels-shiny", "Шины", CategoryEntityType.object, 10),
    ("transport-tires-wheels", "transport-tires-wheels-diski", "Диски", CategoryEntityType.object, 20),
    ("transport-tires-wheels", "transport-tires-wheels-kolesa-v-sbore", "Колёса в сборе", CategoryEntityType.object, 30),
    ("transport-tires-wheels", "transport-tires-wheels-aksessuary-dlya-shin-i-diskov", "Аксессуары для шин и дисков", CategoryEntityType.object, 40),
    ("transport-auto-services", "transport-auto-services-remont-i-obsluzhivanie", "Ремонт и обслуживание", CategoryEntityType.object, 10),
    ("transport-auto-services", "transport-auto-services-avtoelektrika", "Автоэлектрика", CategoryEntityType.object, 20),
    ("transport-auto-services", "transport-auto-services-kuzovnoy-remont", "Кузовной ремонт", CategoryEntityType.object, 30),
    ("transport-auto-services", "transport-auto-services-deteyling-i-uhod", "Детейлинг и уход", CategoryEntityType.object, 40),
    ("transport-auto-services", "transport-auto-services-shinomontazh", "Шиномонтаж", CategoryEntityType.object, 50),
    ("transport-auto-services", "transport-auto-services-evakuatsiya-i-pomosch-na-doroge", "Эвакуация и помощь на дороге", CategoryEntityType.object, 60),
    ("transport-auto-services", "transport-auto-services-tyuning-i-doosnaschenie", "Тюнинг и дооснащение", CategoryEntityType.object, 70),
    ("transport-auto-services", "transport-auto-services-avtostekla", "Автостекла", CategoryEntityType.object, 80),
    ("transport-auto-services", "transport-auto-services-gbo-gazoballonnoe-oborudovanie", "ГБО (газобаллонное оборудование)", CategoryEntityType.object, 90),
    ("transport-auto-services", "transport-auto-services-proverka-i-oformlenie", "Проверка и оформление", CategoryEntityType.object, 100),
    ("transport-moto-tech", "transport-moto-tech-mototsikly", "Мотоциклы", CategoryEntityType.object, 10),
    ("transport-moto-tech", "transport-moto-tech-skutery-i-mopedy", "Скутеры и мопеды", CategoryEntityType.object, 20),
    ("transport-moto-tech", "transport-moto-tech-kvadrotsikly", "Квадроциклы", CategoryEntityType.object, 30),
    ("transport-moto-tech", "transport-moto-tech-baggi", "Багги", CategoryEntityType.object, 40),
    ("transport-moto-tech", "transport-moto-tech-snegohody", "Снегоходы", CategoryEntityType.object, 50),
    ("transport-moto-tech", "transport-moto-tech-elektromototsikly", "Электромотоциклы", CategoryEntityType.object, 60),
    ("transport-moto-tech", "transport-moto-tech-elektroskutery", "Электроскутеры", CategoryEntityType.object, 70),
    ("transport-moto-tech", "transport-moto-tech-elektrokvadrotsikly", "Электроквадроциклы", CategoryEntityType.object, 80),
    ("transport-moto-tech", "transport-moto-tech-zapchasti-dlya-mototehniki", "Запчасти для мототехники", CategoryEntityType.object, 90),
    ("transport-moto-tech", "transport-moto-tech-ekipirovka-i-aksessuary", "Экипировка и аксессуары", CategoryEntityType.object, 100),
    ("transport-moto-tech", "transport-moto-tech-motouslugi", "Мотоуслуги", CategoryEntityType.object, 110),
    ("transport-electric", "transport-electric-elektrosamokaty", "Электросамокаты", CategoryEntityType.object, 10),
    ("transport-electric", "transport-electric-giroskutery", "Гироскутеры", CategoryEntityType.object, 20),
    ("transport-electric", "transport-electric-monokolesa", "Моноколёса", CategoryEntityType.object, 30),
    ("transport-electric", "transport-electric-sigvei-i-mini-sigvei", "Сигвеи и мини-сигвеи", CategoryEntityType.object, 40),
    ("transport-electric", "transport-electric-elektrobaggi", "Электробагги", CategoryEntityType.object, 50),
    ("transport-electric", "transport-electric-elektrokarty", "Электрокарты", CategoryEntityType.object, 60),
    ("transport-electric", "transport-electric-elektrotrayki", "Электротрайки", CategoryEntityType.object, 70),
    ("transport-electric", "transport-electric-elektricheskie-mini-mobili", "Электрические мини-мобили", CategoryEntityType.object, 80),
    ("transport-electric", "transport-electric-drugoy-redkiy-elektrotransport", "Другой редкий электротранспорт", CategoryEntityType.object, 90),
    ("transport-electric", "transport-electric-zapchasti-dlya-elektrotransporta", "Запчасти для электротранспорта", CategoryEntityType.object, 100),
    ("transport-electric", "transport-electric-aksessuary-dlya-elektrotransporta", "Аксессуары для электротранспорта", CategoryEntityType.object, 110),
    ("transport-electric", "transport-electric-remont-i-obsluzhivanie", "Ремонт и обслуживание", CategoryEntityType.object, 120),
    ("transport-commercial", "transport-commercial-malotonnazhnye-gruzoviki", "Малотоннажные грузовики", CategoryEntityType.object, 10),
    ("transport-commercial", "transport-commercial-mikroavtobusy", "Микроавтобусы", CategoryEntityType.object, 20),
    ("transport-commercial", "transport-commercial-furgony", "Фургоны", CategoryEntityType.object, 30),
    ("transport-commercial", "transport-commercial-pikapy", "Пикапы", CategoryEntityType.object, 40),
    ("transport-commercial", "transport-commercial-avtobusy", "Автобусы", CategoryEntityType.object, 50),
    ("transport-commercial", "transport-commercial-spetsavtomobili", "Спецавтомобили", CategoryEntityType.object, 60),
    ("transport-commercial", "transport-commercial-zapchasti", "Запчасти", CategoryEntityType.object, 70),
    ("transport-commercial", "transport-commercial-remont-i-obsluzhivanie", "Ремонт и обслуживание", CategoryEntityType.object, 80),
    ("transport-bicycles", "transport-bicycles-gornye-velosipedy", "Горные велосипеды", CategoryEntityType.object, 10),
    ("transport-bicycles", "transport-bicycles-gorodskie-velosipedy", "Городские велосипеды", CategoryEntityType.object, 20),
    ("transport-bicycles", "transport-bicycles-shosseynye-velosipedy", "Шоссейные велосипеды", CategoryEntityType.object, 30),
    ("transport-bicycles", "transport-bicycles-bmx", "BMX", CategoryEntityType.object, 40),
    ("transport-bicycles", "transport-bicycles-podrostkovye-velosipedy", "Подростковые велосипеды", CategoryEntityType.object, 50),
    ("transport-bicycles", "transport-bicycles-skladnye-velosipedy", "Складные велосипеды", CategoryEntityType.object, 60),
    ("transport-bicycles", "transport-bicycles-elektrovelosipedy", "Электровелосипеды", CategoryEntityType.object, 70),
    ("transport-bicycles", "transport-bicycles-velozapchasti", "Велозапчасти", CategoryEntityType.object, 80),
    ("transport-bicycles", "transport-bicycles-veloaksessuary", "Велоаксессуары", CategoryEntityType.object, 90),
    ("transport-bicycles", "transport-bicycles-veloservis", "Велосервис", CategoryEntityType.object, 100),
    ("transport-special-equipment", "transport-special-equipment-ekskavatory", "Экскаваторы", CategoryEntityType.object, 10),
    ("transport-special-equipment", "transport-special-equipment-pogruzchiki", "Погрузчики", CategoryEntityType.object, 20),
    ("transport-special-equipment", "transport-special-equipment-avtokrany", "Автокраны", CategoryEntityType.object, 30),
    ("transport-special-equipment", "transport-special-equipment-avtovyshki", "Автовышки", CategoryEntityType.object, 40),
    ("transport-special-equipment", "transport-special-equipment-buldozery", "Бульдозеры", CategoryEntityType.object, 50),
    ("transport-special-equipment", "transport-special-equipment-katki", "Катки", CategoryEntityType.object, 60),
    ("transport-special-equipment", "transport-special-equipment-greydery", "Грейдеры", CategoryEntityType.object, 70),
    ("transport-special-equipment", "transport-special-equipment-manipulyatory", "Манипуляторы", CategoryEntityType.object, 80),
    ("transport-special-equipment", "transport-special-equipment-betonotehnika", "Бетонотехника", CategoryEntityType.object, 90),
    ("transport-special-equipment", "transport-special-equipment-dorozhnaya-tehnika", "Дорожная техника", CategoryEntityType.object, 100),
    ("transport-special-equipment", "transport-special-equipment-kommunalnaya-tehnika", "Коммунальная техника", CategoryEntityType.object, 110),
    ("transport-special-equipment", "transport-special-equipment-burovaya-tehnika", "Буровая техника", CategoryEntityType.object, 120),
    ("transport-special-equipment", "transport-special-equipment-drobilno-sortirovochnaya-tehnika", "Дробильно-сортировочная техника", CategoryEntityType.object, 130),
    ("transport-special-equipment", "transport-special-equipment-zapchasti-dlya-spetstehniki", "Запчасти для спецтехники", CategoryEntityType.object, 140),
    ("transport-special-equipment", "transport-special-equipment-remont-i-obsluzhivanie", "Ремонт и обслуживание", CategoryEntityType.object, 150),
    ("transport-cargo", "transport-cargo-samosvaly", "Самосвалы", CategoryEntityType.object, 10),
    ("transport-cargo", "transport-cargo-tyagachi", "Тягачи", CategoryEntityType.object, 20),
    ("transport-cargo", "transport-cargo-bortovye-gruzoviki", "Бортовые грузовики", CategoryEntityType.object, 30),
    ("transport-cargo", "transport-cargo-furgony", "Фургоны", CategoryEntityType.object, 40),
    ("transport-cargo", "transport-cargo-spetsgruzoviki", "Спецгрузовики", CategoryEntityType.object, 50),
    ("transport-cargo", "transport-cargo-zapchasti", "Запчасти", CategoryEntityType.object, 60),
    ("transport-cargo", "transport-cargo-remont-i-obsluzhivanie", "Ремонт и обслуживание", CategoryEntityType.object, 70),
    ("transport-watercraft", "transport-watercraft-lodki", "Лодки", CategoryEntityType.object, 10),
    ("transport-watercraft", "transport-watercraft-katera", "Катера", CategoryEntityType.object, 20),
    ("transport-watercraft", "transport-watercraft-yahty", "Яхты", CategoryEntityType.object, 30),
    ("transport-watercraft", "transport-watercraft-gidrotsikly", "Гидроциклы", CategoryEntityType.object, 40),
    ("transport-watercraft", "transport-watercraft-naduvnye-lodki", "Надувные лодки", CategoryEntityType.object, 50),
    ("transport-watercraft", "transport-watercraft-lodochnye-motory", "Лодочные моторы", CategoryEntityType.object, 60),
    ("transport-watercraft", "transport-watercraft-pritsepy-dlya-vodnogo-transporta", "Прицепы для водного транспорта", CategoryEntityType.object, 70),
    ("transport-watercraft", "transport-watercraft-zapchasti-i-komplektuyuschie", "Запчасти и комплектующие", CategoryEntityType.object, 80),
    ("transport-watercraft", "transport-watercraft-aksessuary-i-oborudovanie", "Аксессуары и оборудование", CategoryEntityType.object, 90),
    ("transport-watercraft", "transport-watercraft-remont-i-obsluzhivanie", "Ремонт и обслуживание", CategoryEntityType.object, 100),
    ("transport-trailers", "transport-trailers-dlya-legkovyh-avtomobiley", "Для легковых автомобилей", CategoryEntityType.object, 10),
    ("transport-trailers", "transport-trailers-gruzovye-pritsepy", "Грузовые прицепы", CategoryEntityType.object, 20),
    ("transport-trailers", "transport-trailers-polupritsepy", "Полуприцепы", CategoryEntityType.object, 30),
    ("transport-trailers", "transport-trailers-samosvalnye-pritsepy", "Самосвальные прицепы", CategoryEntityType.object, 40),
    ("transport-trailers", "transport-trailers-tentovannye-pritsepy", "Тентованные прицепы", CategoryEntityType.object, 50),
    ("transport-trailers", "transport-trailers-refrizheratornye-pritsepy", "Рефрижераторные прицепы", CategoryEntityType.object, 60),
    ("transport-trailers", "transport-trailers-tsisterny", "Цистерны", CategoryEntityType.object, 70),
    ("transport-trailers", "transport-trailers-traly-i-nizkoramnye", "Тралы и низкорамные", CategoryEntityType.object, 80),
    ("transport-trailers", "transport-trailers-spetsializirovannye-pritsepy", "Специализированные прицепы", CategoryEntityType.object, 90),
    ("transport-trailers", "transport-trailers-zapchasti-i-komplektuyuschie", "Запчасти и комплектующие", CategoryEntityType.object, 100),
    ("transport-trailers", "transport-trailers-remont-i-obsluzhivanie", "Ремонт и обслуживание", CategoryEntityType.object, 110),
    ("transport-farm-machinery", "transport-farm-machinery-traktory", "Тракторы", CategoryEntityType.object, 10),
    ("transport-farm-machinery", "transport-farm-machinery-kombayny", "Комбайны", CategoryEntityType.object, 20),
    ("transport-farm-machinery", "transport-farm-machinery-posevnaya-tehnika", "Посевная техника", CategoryEntityType.object, 30),
    ("transport-farm-machinery", "transport-farm-machinery-pochvoobrabatyvayuschaya-tehnika", "Почвообрабатывающая техника", CategoryEntityType.object, 40),
    ("transport-farm-machinery", "transport-farm-machinery-tehnika-dlya-zagotovki-kormov", "Техника для заготовки кормов", CategoryEntityType.object, 50),
    ("transport-farm-machinery", "transport-farm-machinery-opryskivateli", "Опрыскиватели", CategoryEntityType.object, 60),
    ("transport-farm-machinery", "transport-farm-machinery-navesnoe-oborudovanie", "Навесное оборудование", CategoryEntityType.object, 70),
    ("transport-farm-machinery", "transport-farm-machinery-pritsepy-dlya-selhoztehniki", "Прицепы для сельхозтехники", CategoryEntityType.object, 80),
    ("transport-farm-machinery", "transport-farm-machinery-zapchasti-dlya-selhoztehniki", "Запчасти для сельхозтехники", CategoryEntityType.object, 90),
    ("transport-farm-machinery", "transport-farm-machinery-remont-i-obsluzhivanie", "Ремонт и обслуживание", CategoryEntityType.object, 100),
    ("transport-rental", "transport-rental-legkovye-avtomobili", "Легковые автомобили", CategoryEntityType.object, 10),
    ("transport-rental", "transport-rental-vnedorozhniki-i-krossovery", "Внедорожники и кроссоверы", CategoryEntityType.object, 20),
    ("transport-rental", "transport-rental-mikroavtobusy", "Микроавтобусы", CategoryEntityType.object, 30),
    ("transport-rental", "transport-rental-avtobusy", "Автобусы", CategoryEntityType.object, 40),
    ("transport-rental", "transport-rental-gruzovoy-transport", "Грузовой транспорт", CategoryEntityType.object, 50),
    ("transport-rental", "transport-rental-kommercheskiy-transport", "Коммерческий транспорт", CategoryEntityType.object, 60),
    ("transport-rental", "transport-rental-spetstehnika", "Спецтехника", CategoryEntityType.object, 70),
    ("transport-rental", "transport-rental-mototehnika", "Мототехника", CategoryEntityType.object, 80),
    ("transport-rental", "transport-rental-vodnyy-transport", "Водный транспорт", CategoryEntityType.object, 90),
    ("transport-rental", "transport-rental-elektrotransport", "Электротранспорт", CategoryEntityType.object, 100),
    ("transport-rental", "transport-rental-arenda-s-voditelem", "Аренда с водителем", CategoryEntityType.object, 110),
    ("transport-rental", "transport-rental-dolgosrochnaya-arenda", "Долгосрочная аренда", CategoryEntityType.object, 120),
    ("transport-buyback-exchange", "transport-buyback-exchange-skupka-avtomobiley", "Скупка автомобилей", CategoryEntityType.object, 10),
    ("transport-buyback-exchange", "transport-buyback-exchange-skupka-kommercheskogo-transporta", "Скупка коммерческого транспорта", CategoryEntityType.object, 20),
    ("transport-buyback-exchange", "transport-buyback-exchange-skupka-gruzovogo-transporta", "Скупка грузового транспорта", CategoryEntityType.object, 30),
    ("transport-buyback-exchange", "transport-buyback-exchange-skupka-spetstehniki", "Скупка спецтехники", CategoryEntityType.object, 40),
    ("transport-buyback-exchange", "transport-buyback-exchange-skupka-mototehniki", "Скупка мототехники", CategoryEntityType.object, 50),
    ("transport-buyback-exchange", "transport-buyback-exchange-obmen-transporta", "Обмен транспорта", CategoryEntityType.object, 60),
    ("transport-buyback-exchange", "transport-buyback-exchange-vykup-posle-dtp", "Выкуп после ДТП", CategoryEntityType.object, 70),
    ("transport-buyback-exchange", "transport-buyback-exchange-vykup-na-zapchasti", "Выкуп на запчасти", CategoryEntityType.object, 80),
    ("real-estate", "real-estate-kvartiry", "Квартиры", CategoryEntityType.object, 10),
    ("real-estate", "real-estate-doma-i-kottedzhi", "Дома и коттеджи", CategoryEntityType.object, 20),
    ("real-estate", "real-estate-novostroyki", "Новостройки", CategoryEntityType.object, 30),
    ("real-estate", "real-estate-komnaty", "Комнаты", CategoryEntityType.object, 40),
    ("real-estate", "real-estate-kommercheskaya-nedvizhimost", "Коммерческая недвижимость", CategoryEntityType.object, 50),
    ("real-estate", "real-estate-zemelnye-uchastki", "Земельные участки", CategoryEntityType.object, 60),
    ("real-estate", "real-estate-garazhi-i-parkovki", "Гаражи и парковки", CategoryEntityType.object, 70),
    ("real-estate", "real-estate-dachi-i-zagorodnaya-nedvizhimost", "Дачи и загородная недвижимость", CategoryEntityType.object, 80),
    ("real-estate", "real-estate-nedvizhimost-za-rubezhom", "Недвижимость за рубежом", CategoryEntityType.object, 90),
    ("real-estate", "real-estate-obmen-nedvizhimosti", "Обмен недвижимости", CategoryEntityType.object, 100),
    ("jobs", "jobs-shveynoe-proizvodstvo", "Швейное производство", CategoryEntityType.job, 10),
    ("jobs", "jobs-proizvodstvo-i-promyshlennost", "Производство и промышленность", CategoryEntityType.job, 20),
    ("jobs", "jobs-stroitelstvo-i-remont", "Строительство и ремонт", CategoryEntityType.job, 30),
    ("jobs", "jobs-transport-i-logistika", "Транспорт и логистика", CategoryEntityType.job, 40),
    ("jobs", "jobs-prodazhi-i-torgovlya", "Продажи и торговля", CategoryEntityType.job, 50),
    ("jobs", "jobs-ofis-i-administratsiya", "Офис и администрация", CategoryEntityType.job, 60),
    ("jobs", "jobs-buhgalteriya-i-finansy", "Бухгалтерия и финансы", CategoryEntityType.job, 70),
    ("jobs", "jobs-marketing-reklama-i-media", "Маркетинг, реклама и медиа", CategoryEntityType.job, 80),
    ("jobs", "jobs-it-i-tehnologii", "IT и технологии", CategoryEntityType.job, 90),
    ("jobs", "jobs-obrazovanie-i-obuchenie", "Образование и обучение", CategoryEntityType.job, 100),
    ("jobs", "jobs-meditsina-i-farmatsevtika", "Медицина и фармацевтика", CategoryEntityType.job, 110),
    ("jobs", "jobs-krasota-i-zdorove", "Красота и здоровье", CategoryEntityType.job, 120),
    ("jobs", "jobs-gostinitsy-kafe-i-restorany", "Гостиницы, кафе и рестораны", CategoryEntityType.job, 130),
    ("jobs", "jobs-sto-i-avtoservis", "СТО и автосервис", CategoryEntityType.job, 140),
    ("jobs", "jobs-razvlecheniya-i-sport", "Развлечения и спорт", CategoryEntityType.job, 150),
    ("jobs", "jobs-domashniy-personal", "Домашний персонал", CategoryEntityType.job, 160),
    ("jobs", "jobs-ohrana-i-bezopasnost", "Охрана и безопасность", CategoryEntityType.job, 170),
    ("jobs", "jobs-selskoe-hozyaystvo", "Сельское хозяйство", CategoryEntityType.job, 180),
    ("jobs", "jobs-studenty-i-podrabotka", "Студенты и подработка", CategoryEntityType.job, 190),
    ("jobs", "jobs-rabota-za-rubezhom", "Работа за рубежом", CategoryEntityType.job, 200),
    ("jobs", "jobs-vakansii-bez-opyta", "Вакансии без опыта", CategoryEntityType.job, 210),
    ("jobs", "jobs-rezyume-soiskateley", "Резюме соискателей", CategoryEntityType.job, 220),
    ("services", "services-stroitelnye-i-remontnye-uslugi", "Строительные и ремонтные услуги", CategoryEntityType.service, 10),
    ("services", "services-santehnika", "Сантехника", CategoryEntityType.service, 20),
    ("services", "services-elektrika", "Электрика", CategoryEntityType.service, 30),
    ("services", "services-otoplenie-i-klimat", "Отопление и климат", CategoryEntityType.service, 40),
    ("services", "services-mebel-i-interer", "Мебель и интерьер", CategoryEntityType.service, 50),
    ("services", "services-bytovye-uslugi", "Бытовые услуги", CategoryEntityType.service, 60),
    ("services", "services-uborka-i-klining", "Уборка и клининг", CategoryEntityType.service, 70),
    ("services", "services-himchistka-i-prachechnye-uslugi", "Химчистка и прачечные услуги", CategoryEntityType.service, 80),
    ("services", "services-dezinfektsiya-i-sanitarnye-uslugi", "Дезинфекция и санитарные услуги", CategoryEntityType.service, 90),
    ("services", "services-meditsinskie-uslugi", "Медицинские услуги", CategoryEntityType.service, 100),
    ("services", "services-remont-tehniki", "Ремонт техники", CategoryEntityType.service, 110),
    ("services", "services-ustanovka-i-podklyuchenie-tehniki", "Установка и подключение техники", CategoryEntityType.service, 120),
    ("services", "services-arenda-instrumentov-oborud-niya", "Аренда инструментов/оборуд.ния", CategoryEntityType.service, 130),
    ("services", "services-ritualnye-uslugi", "Ритуальные услуги", CategoryEntityType.service, 140),
    ("services", "services-avariynoe-vskrytie-zamkov", "Аварийное вскрытие замков", CategoryEntityType.service, 150),
    ("services", "services-skupka-i-pererabotka-vtorsyrya", "Скупка и переработка вторсырья", CategoryEntityType.service, 160),
    ("services", "services-poligrafiya-i-pechatnye-uslugi", "Полиграфия и печатные услуги", CategoryEntityType.service, 170),
    ("services", "services-kompyutery-i-it-uslugi", "Компьютеры и IT-услуги", CategoryEntityType.service, 180),
    ("services", "services-reklama-i-marketing", "Реклама и маркетинг", CategoryEntityType.service, 190),
    ("services", "services-foto-i-videosemka", "Фото и видеосъёмка", CategoryEntityType.service, 200),
    ("services", "services-uslugi-krasoty-i-stilya", "Услуги красоты и стиля", CategoryEntityType.service, 210),
    ("services", "services-atele-i-poshiv-odezhdy", "Ателье и пошив одежды", CategoryEntityType.service, 220),
    ("services", "services-uslugi-dizayna-i-proektirovaniya", "Услуги дизайна и проектирования", CategoryEntityType.service, 230),
    ("services", "services-organizatsiya-meropriyatiy", "Организация мероприятий", CategoryEntityType.service, 240),
    ("services", "services-muzykalnye-uslugi", "Музыкальные услуги", CategoryEntityType.service, 250),
    ("services", "services-obuchenie-i-repetitorstvo", "Обучение и репетиторство", CategoryEntityType.service, 260),
    ("services", "services-perevody-i-rabota-s-tekstom", "Переводы и работа с текстом", CategoryEntityType.service, 270),
    ("services", "services-yuridicheskie-uslugi", "Юридические услуги", CategoryEntityType.service, 280),
    ("services", "services-buhgalterskie-uslugi", "Бухгалтерские услуги", CategoryEntityType.service, 290),
    ("services", "services-finansovye-uslugi", "Финансовые услуги", CategoryEntityType.service, 300),
    ("services", "services-uslugi-spetstehniki", "Услуги спецтехники", CategoryEntityType.service, 310),
    ("services", "services-gruzoperevozki-i-pereezdy", "Грузоперевозки и переезды", CategoryEntityType.service, 320),
    ("services", "services-kurerskie-uslugi", "Курьерские услуги", CategoryEntityType.service, 330),
    ("services", "services-turizm-i-vizovaya-podderzhka", "Туризм и визовая поддержка", CategoryEntityType.service, 340),
    ("services", "services-domashniy-personal", "Домашний персонал", CategoryEntityType.service, 350),
    ("services", "services-selskohozyaystvennye-uslugi", "Сельскохозяйственные услуги", CategoryEntityType.service, 360),
    ("services", "services-ohrana-i-bezopasnost", "Охрана и безопасность", CategoryEntityType.service, 370),
    ("services", "services-prochie-uslugi", "Прочие услуги", CategoryEntityType.service, 380),
    ("repair-construction", "repair-construction-stroitelnye-materialy", "Строительные материалы", CategoryEntityType.construction, 10),
    ("repair-construction", "repair-construction-kirpichi-i-stroitelnye-bloki", "Кирпичи и строительные блоки", CategoryEntityType.construction, 20),
    ("repair-construction", "repair-construction-tsement-smesi-sypuchie-materialy", "Цемент/смеси/сыпучие материалы", CategoryEntityType.construction, 30),
    ("repair-construction", "repair-construction-pilomaterialy", "Пиломатериалы", CategoryEntityType.construction, 40),
    ("repair-construction", "repair-construction-metalloprokat", "Металлопрокат", CategoryEntityType.construction, 50),
    ("repair-construction", "repair-construction-krovlya-i-vodostoki", "Кровля и водостоки", CategoryEntityType.construction, 60),
    ("repair-construction", "repair-construction-fasady-i-uteplenie", "Фасады и утепление", CategoryEntityType.construction, 70),
    ("repair-construction", "repair-construction-okna-i-dveri", "Окна и двери", CategoryEntityType.construction, 80),
    ("repair-construction", "repair-construction-napolnye-pokrytiya", "Напольные покрытия", CategoryEntityType.construction, 90),
    ("repair-construction", "repair-construction-stenovye-materialy-pokrytiya", "Стеновые материалы/покрытия", CategoryEntityType.construction, 100),
    ("repair-construction", "repair-construction-potolki-i-potolochnye-sistemy", "Потолки и потолочные системы", CategoryEntityType.construction, 110),
    ("repair-construction", "repair-construction-plitka-i-keramogranit", "Плитка и керамогранит", CategoryEntityType.construction, 120),
    ("repair-construction", "repair-construction-lakokrasochnye-materialy", "Лакокрасочные материалы", CategoryEntityType.construction, 130),
    ("repair-construction", "repair-construction-klei-i-stroitelnaya-himiya", "Клеи и строительная химия", CategoryEntityType.construction, 140),
    ("repair-construction", "repair-construction-otdelochnye-materialy", "Отделочные материалы", CategoryEntityType.construction, 150),
    ("repair-construction", "repair-construction-santehnika-i-vodosnabzhenie", "Сантехника и водоснабжение", CategoryEntityType.construction, 160),
    ("repair-construction", "repair-construction-elektrika-i-osveschenie", "Электрика и освещение", CategoryEntityType.construction, 170),
    ("repair-construction", "repair-construction-otoplenie-ventilyatsiya-i-klimat", "Отопление, вентиляция и климат", CategoryEntityType.construction, 180),
    ("repair-construction", "repair-construction-instrumenty", "Инструменты", CategoryEntityType.construction, 190),
    ("repair-construction", "repair-construction-elektroinstrumenty", "Электроинструменты", CategoryEntityType.construction, 200),
    ("repair-construction", "repair-construction-spetsodezhda-i-sredstva-zaschity", "Спецодежда и средства защиты", CategoryEntityType.construction, 210),
    ("repair-construction", "repair-construction-stroitelnoe-oborudovanie", "Строительное оборудование", CategoryEntityType.construction, 220),
    ("repair-construction", "repair-construction-lestnitsy-i-stroitelnye-lesa", "Лестницы и строительные леса", CategoryEntityType.construction, 230),
    ("repair-construction", "repair-construction-zabory-vorota-i-ograzhdeniya", "Заборы, ворота и ограждения", CategoryEntityType.construction, 240),
    ("repair-construction", "repair-construction-navesy-i-metallokonstruktsii", "Навесы и металлоконструкции", CategoryEntityType.construction, 250),
    ("repair-construction", "repair-construction-kovanye-izdeliya", "Кованые изделия", CategoryEntityType.construction, 260),
    ("repair-construction", "repair-construction-krepezh-i-rashodnye-materialy", "Крепеж и расходные материалы", CategoryEntityType.construction, 270),
    ("repair-construction", "repair-construction-prochee-dlya-remonta-stroitelstva", "Прочее для ремонта/строительства", CategoryEntityType.construction, 280),
    ("electronics", "electronics-smartfony-i-telefony", "Смартфоны и телефоны", CategoryEntityType.object, 10),
    ("electronics", "electronics-planshety-i-elektronnye-knigi", "Планшеты и электронные книги", CategoryEntityType.object, 20),
    ("electronics", "electronics-noutbuki-i-kompyutery", "Ноутбуки и компьютеры", CategoryEntityType.object, 30),
    ("electronics", "electronics-komplektuyuschie-dlya-kompyuterov", "Комплектующие для компьютеров", CategoryEntityType.object, 40),
    ("electronics", "electronics-orgtehnika", "Оргтехника", CategoryEntityType.object, 50),
    ("electronics", "electronics-televizory-i-proektory", "Телевизоры и проекторы", CategoryEntityType.object, 60),
    ("electronics", "electronics-audiotehnika", "Аудиотехника", CategoryEntityType.object, 70),
    ("electronics", "electronics-foto-i-videotehnika", "Фото и видеотехника", CategoryEntityType.object, 80),
    ("electronics", "electronics-igrovye-pristavki-i-aksessuary", "Игровые приставки и аксессуары", CategoryEntityType.object, 90),
    ("electronics", "electronics-umnye-chasy-i-gadzhety", "Умные часы и гаджеты", CategoryEntityType.object, 100),
    ("electronics", "electronics-setevoe-oborudovanie", "Сетевое оборудование", CategoryEntityType.object, 110),
    ("electronics", "electronics-tehnika-dlya-ofisa", "Техника для офиса", CategoryEntityType.object, 120),
    ("electronics", "electronics-bytovaya-tehnika", "Бытовая техника", CategoryEntityType.object, 130),
    ("electronics", "electronics-klimaticheskaya-tehnika", "Климатическая техника", CategoryEntityType.object, 140),
    ("electronics", "electronics-vstraivaemaya-tehnika", "Встраиваемая техника", CategoryEntityType.object, 150),
    ("electronics", "electronics-kuhonnaya-tehnika", "Кухонная техника", CategoryEntityType.object, 160),
    ("electronics", "electronics-tehnika-dlya-doma", "Техника для дома", CategoryEntityType.object, 170),
    ("electronics", "electronics-zapchasti-i-aksessuary", "Запчасти и аксессуары", CategoryEntityType.object, 180),
    ("electronics", "electronics-prochaya-tehnika-i-elektronika", "Прочая техника и электроника", CategoryEntityType.object, 190),
    ("beauty", "beauty-kosmetika", "Косметика", CategoryEntityType.object, 10),
    ("beauty", "beauty-parfyumeriya", "Парфюмерия", CategoryEntityType.object, 20),
    ("beauty", "beauty-uhod-za-volosami", "Уход за волосами", CategoryEntityType.object, 30),
    ("beauty", "beauty-uhod-za-litsom", "Уход за лицом", CategoryEntityType.object, 40),
    ("beauty", "beauty-uhod-za-telom", "Уход за телом", CategoryEntityType.object, 50),
    ("beauty", "beauty-muzhskoy-uhod-i-brite", "Мужской уход и бритьё", CategoryEntityType.object, 60),
    ("beauty", "beauty-manikyur-i-pedikyur", "Маникюр и педикюр", CategoryEntityType.object, 70),
    ("beauty", "beauty-brovi-resnitsy-i-guby", "Брови, ресницы и губы", CategoryEntityType.object, 80),
    ("beauty", "beauty-depilyatsiya-i-epilyatsiya", "Депиляция и эпиляция", CategoryEntityType.object, 90),
    ("beauty", "beauty-professionalnaya-kosmetika", "Профессиональная косметика", CategoryEntityType.object, 100),
    ("beauty", "beauty-instrumenty-oborud-e-dlya-krasoty", "Инструменты/оборуд.е для красоты", CategoryEntityType.object, 110),
    ("beauty", "beauty-rashodnye-materialy-dlya-salonov", "Расходные материалы для салонов", CategoryEntityType.object, 120),
    ("beauty", "beauty-sredstva-gigieny", "Средства гигиены", CategoryEntityType.object, 130),
    ("beauty", "beauty-tovary-dlya-barbershopov", "Товары для барбершопов", CategoryEntityType.object, 140),
    ("beauty", "beauty-tovary-dlya-tatu-i-pirsinga", "Товары для тату и пирсинга", CategoryEntityType.object, 150),
    ("beauty", "beauty-prochee-dlya-krasoty-i-uhoda", "Прочее для красоты и ухода", CategoryEntityType.object, 160),
    ("fashion", "fashion-zhenskaya-odezhda", "Женская одежда", CategoryEntityType.object, 10),
    ("fashion", "fashion-muzhskaya-odezhda", "Мужская одежда", CategoryEntityType.object, 20),
    ("fashion", "fashion-odezhda-dlya-beremennyh-kormyaschih", "Одежда для беременных/кормящих", CategoryEntityType.object, 30),
    ("fashion", "fashion-nizhnee-bele", "Нижнее бельё", CategoryEntityType.object, 40),
    ("fashion", "fashion-domashnyaya-odezhda", "Домашняя одежда", CategoryEntityType.object, 50),
    ("fashion", "fashion-musulmanskaya-odezhda-aksessuary", "Мусульманская одежда/аксессуары", CategoryEntityType.object, 60),
    ("fashion", "fashion-zhenskaya-obuv", "Женская обувь", CategoryEntityType.object, 70),
    ("fashion", "fashion-muzhskaya-obuv", "Мужская обувь", CategoryEntityType.object, 80),
    ("fashion", "fashion-sumki-i-chemodany", "Сумки и чемоданы", CategoryEntityType.object, 90),
    ("fashion", "fashion-ukrasheniya-i-bizhuteriya", "Украшения и бижутерия", CategoryEntityType.object, 100),
    ("fashion", "fashion-chasy", "Часы", CategoryEntityType.object, 110),
    ("fashion", "fashion-aksessuary", "Аксессуары", CategoryEntityType.object, 120),
    ("fashion", "fashion-tkani-i-furnitura", "Ткани и фурнитура", CategoryEntityType.object, 130),
    ("fashion", "fashion-spetsodezhda-i-uniforma", "Спецодежда и униформа", CategoryEntityType.object, 140),
    ("fashion", "fashion-natsionalnaya-odezhda", "Национальная одежда", CategoryEntityType.object, 150),
    ("fashion", "fashion-svadebnaya-i-vechernyaya-odezhda", "Свадебная и вечерняя одежда", CategoryEntityType.object, 160),
    ("fashion", "fashion-sportivnaya-odezhda-i-obuv", "Спортивная одежда и обувь", CategoryEntityType.object, 170),
    ("fashion", "fashion-prochee", "Прочее", CategoryEntityType.object, 180),
    ("food-agri", "food-agri-ovoschi-i-frukty", "Овощи и фрукты", CategoryEntityType.food, 10),
    ("food-agri", "food-agri-myaso-i-myasnaya-produktsiya", "Мясо и мясная продукция", CategoryEntityType.food, 20),
    ("food-agri", "food-agri-molochnaya-produktsiya", "Молочная продукция", CategoryEntityType.food, 30),
    ("food-agri", "food-agri-yaytsa", "Яйца", CategoryEntityType.food, 40),
    ("food-agri", "food-agri-ryba-i-moreprodukty", "Рыба и морепродукты", CategoryEntityType.food, 50),
    ("food-agri", "food-agri-med-i-produkty-pchelovodstva", "Мёд и продукты пчеловодства", CategoryEntityType.food, 60),
    ("food-agri", "food-agri-orehi-i-suhofrukty", "Орехи и сухофрукты", CategoryEntityType.food, 70),
    ("food-agri", "food-agri-krupy-muka-makaronnye-izdeliya", "Крупы, мука/макаронные изделия", CategoryEntityType.food, 80),
    ("food-agri", "food-agri-masla-i-zhiry", "Масла и жиры", CategoryEntityType.food, 90),
    ("food-agri", "food-agri-spetsii-pripravy-i-pryanosti", "Специи, приправы и пряности", CategoryEntityType.food, 100),
    ("food-agri", "food-agri-bakaleya-i-produkty-pitaniya", "Бакалея и продукты питания", CategoryEntityType.food, 110),
    ("food-agri", "food-agri-konditerskie-izdeliya-i-sladosti", "Кондитерские изделия и сладости", CategoryEntityType.food, 120),
    ("food-agri", "food-agri-hlebobulochnye-izdeliya", "Хлебобулочные изделия", CategoryEntityType.food, 130),
    ("food-agri", "food-agri-sneki-i-zakuski", "Снеки и закуски", CategoryEntityType.food, 140),
    ("food-agri", "food-agri-polufabrikaty", "Полуфабрикаты", CategoryEntityType.food, 150),
    ("food-agri", "food-agri-zamorozhennye-produkty", "Замороженные продукты", CategoryEntityType.food, 160),
    ("food-agri", "food-agri-konservy-i-solenya", "Консервы и соленья", CategoryEntityType.food, 170),
    ("food-agri", "food-agri-kolbasnye-izdeliya-i-delikatesy", "Колбасные изделия и деликатесы", CategoryEntityType.food, 180),
    ("food-agri", "food-agri-gotovaya-eda-i-kulinariya", "Готовая еда и кулинария", CategoryEntityType.food, 190),
    ("food-agri", "food-agri-chay-i-kofe", "Чай и кофе", CategoryEntityType.food, 200),
    ("food-agri", "food-agri-napitki", "Напитки", CategoryEntityType.food, 210),
    ("food-agri", "food-agri-zerno-i-zernovye-kultury", "Зерно и зерновые культуры", CategoryEntityType.food, 220),
    ("food-agri", "food-agri-optovyy-otdel", "Оптовый отдел", CategoryEntityType.food, 230),
    ("food-agri", "food-agri-tara-upakovka-dlya-produktsii", "Тара/упаковка для продукции", CategoryEntityType.food, 240),
    ("food-agri", "food-agri-ekoprodukty-i-fermerskie-tovary", "Экопродукты и фермерские товары", CategoryEntityType.food, 250),
    ("food-agri", "food-agri-prochie-produkty-i-selhoztovary", "Прочие продукты и сельхозтовары", CategoryEntityType.food, 260),
    ("kids", "kids-tovary-dlya-novorozhdennyh", "Товары для новорождённых", CategoryEntityType.object, 10),
    ("kids", "kids-detskaya-odezhda", "Детская одежда", CategoryEntityType.object, 20),
    ("kids", "kids-detskaya-obuv", "Детская обувь", CategoryEntityType.object, 30),
    ("kids", "kids-detskie-kolyaski", "Детские коляски", CategoryEntityType.object, 40),
    ("kids", "kids-avtokresla-i-perenoski", "Автокресла и переноски", CategoryEntityType.object, 50),
    ("kids", "kids-detskoe-pitanie", "Детское питание", CategoryEntityType.object, 60),
    ("kids", "kids-podguzniki-i-gigiena", "Подгузники и гигиена", CategoryEntityType.object, 70),
    ("kids", "kids-igrushki-igry-i-konstruktory", "Игрушки/игры и конструкторы", CategoryEntityType.object, 80),
    ("kids", "kids-detskie-knigi-i-razvitie", "Детские книги и развитие", CategoryEntityType.object, 90),
    ("kids", "kids-tovary-dlya-shkoly", "Товары для школы", CategoryEntityType.object, 100),
    ("kids", "kids-detskaya-mebel", "Детская мебель", CategoryEntityType.object, 110),
    ("kids", "kids-detskiy-transport", "Детский транспорт", CategoryEntityType.object, 120),
    ("kids", "kids-detskiy-sport-aktivnyy-otdyh", "Детский спорт/активный отдых", CategoryEntityType.object, 130),
    ("kids", "kids-detskaya-bezopasnost", "Детская безопасность", CategoryEntityType.object, 140),
    ("kids", "kids-detskoe-zdorove-i-uhod", "Детское здоровье и уход", CategoryEntityType.object, 150),
    ("kids", "kids-detskie-sady-i-obrazovanie", "Детские сады и образование", CategoryEntityType.object, 160),
    ("kids", "kids-detskie-prazdniki-tvorchestvo", "Детские праздники/творчество", CategoryEntityType.object, 170),
    ("kids", "kids-prochie-detskie-tovary", "Прочие детские товары", CategoryEntityType.object, 180),
    ("business-equipment", "business-equipment-torgovoe-oborudovanie", "Торговое оборудование", CategoryEntityType.equipment, 10),
    ("business-equipment", "business-equipment-kassovoe-i-pos-oborudovanie", "Кассовое и POS-оборудование", CategoryEntityType.equipment, 20),
    ("business-equipment", "business-equipment-skladskoe-oborudovanie", "Складское оборудование", CategoryEntityType.equipment, 30),
    ("business-equipment", "business-equipment-holodilnoe-oborudovanie", "Холодильное оборудование", CategoryEntityType.equipment, 40),
    ("business-equipment", "business-equipment-oborudovanie-dlya-obschepita", "Оборудование для общепита", CategoryEntityType.equipment, 50),
    ("business-equipment", "business-equipment-oborudovanie-dlya-salonov-krasoty", "Оборудование для салонов красоты", CategoryEntityType.equipment, 60),
    ("business-equipment", "business-equipment-meditsinskoe-oborudovanie", "Медицинское оборудование", CategoryEntityType.equipment, 70),
    ("business-equipment", "business-equipment-shveynoe-oborudovanie", "Швейное оборудование", CategoryEntityType.equipment, 80),
    ("business-equipment", "business-equipment-proizvodstvennoe-oborudovanie", "Производственное оборудование", CategoryEntityType.equipment, 90),
    ("business-equipment", "business-equipment-upakovka-i-markirovka", "Упаковка и маркировка", CategoryEntityType.equipment, 100),
    ("business-equipment", "business-equipment-poligraficheskoe-oborudovanie", "Полиграфическое оборудование", CategoryEntityType.equipment, 110),
    ("business-equipment", "business-equipment-ofisnoe-oborudovanie", "Офисное оборудование", CategoryEntityType.equipment, 120),
    ("business-equipment", "business-equipment-bankovskoe-oborudovanie", "Банковское оборудование", CategoryEntityType.equipment, 130),
    ("business-equipment", "business-equipment-laboratornoe-oborudovanie", "Лабораторное оборудование", CategoryEntityType.equipment, 140),
    ("business-equipment", "business-equipment-selskohozyaystvennoe-oborud-e", "Сельскохозяйственное оборуд.е", CategoryEntityType.equipment, 150),
    ("business-equipment", "business-equipment-oborudovanie-dlya-gostinits", "Оборудование для гостиниц", CategoryEntityType.equipment, 160),
    ("business-equipment", "business-equipment-oborudovanie-dlya-avtomoek-i-sto", "Оборудование для автомоек и СТО", CategoryEntityType.equipment, 170),
    ("business-equipment", "business-equipment-oborud-nie-dlya-sporta-razvlecheniy", "Оборуд.ние для спорта/развлечений", CategoryEntityType.equipment, 180),
    ("business-equipment", "business-equipment-zapchasti-i-komplektuyuschie", "Запчасти и комплектующие", CategoryEntityType.equipment, 190),
    ("business-equipment", "business-equipment-prochee-oborudovanie-dlya-biznesa", "Прочее оборудование для бизнеса", CategoryEntityType.equipment, 200),
    ("medical", "medical-ortopedicheskie-tovary", "Ортопедические товары", CategoryEntityType.object, 10),
    ("medical", "medical-reabilitatsionnye-tovary", "Реабилитационные товары", CategoryEntityType.object, 20),
    ("medical", "medical-tovary-dlya-uhoda-za-bolnymi", "Товары для ухода за больными", CategoryEntityType.object, 30),
    ("medical", "medical-meditsinskie-pribory", "Медицинские приборы", CategoryEntityType.object, 40),
    ("medical", "medical-rashodnye-med-materialy", "Расходные мед материалы", CategoryEntityType.object, 50),
    ("medical", "medical-sredstva-individ-noy-zaschity", "Средства индивид.ной защиты", CategoryEntityType.object, 60),
    ("medical", "medical-meditsinskaya-odezhda", "Медицинская одежда", CategoryEntityType.object, 70),
    ("medical", "medical-optika-i-tovary-dlya-zreniya", "Оптика и товары для зрения", CategoryEntityType.object, 80),
    ("medical", "medical-tovary-dlya-sluha", "Товары для слуха", CategoryEntityType.object, 90),
    ("medical", "medical-tovary-dlya-diabetikov", "Товары для диабетиков", CategoryEntityType.object, 100),
    ("medical", "medical-ingalyatory-tovary-dlya-dyhaniya", "Ингаляторы/товары для дыхания", CategoryEntityType.object, 110),
    ("medical", "medical-massazh-i-reabilitatsiya", "Массаж и реабилитация", CategoryEntityType.object, 120),
    ("medical", "medical-meditsinskaya-mebel", "Медицинская мебель", CategoryEntityType.object, 130),
    ("medical", "medical-aptechki-i-pervaya-pomosch", "Аптечки и первая помощь", CategoryEntityType.object, 140),
    ("medical", "medical-bady-i-tovary-dlya-zdorovya", "БАДы и товары для здоровья", CategoryEntityType.object, 150),
    ("medical", "medical-prochie-medtovary", "Прочие медтовары", CategoryEntityType.object, 160),
    ("ready-business", "ready-business-magaziny-i-torgovye-tochki", "Магазины и торговые точки", CategoryEntityType.business, 10),
    ("ready-business", "ready-business-kafe-restorany-i-obschepit", "Кафе, рестораны и общепит", CategoryEntityType.business, 20),
    ("ready-business", "ready-business-gostinitsy-i-gostevye-doma", "Гостиницы и гостевые дома", CategoryEntityType.business, 30),
    ("ready-business", "ready-business-salony-krasoty-i-barbershopy", "Салоны красоты и барбершопы", CategoryEntityType.business, 40),
    ("ready-business", "ready-business-shveynye-tseha-i-atele", "Швейные цеха и ателье", CategoryEntityType.business, 50),
    ("ready-business", "ready-business-proizvodstvo-i-tseha", "Производство и цеха", CategoryEntityType.business, 60),
    ("ready-business", "ready-business-avtomoyki-avtouslugi-i-sto", "Автомойки/автоуслуги и СТО", CategoryEntityType.business, 70),
    ("ready-business", "ready-business-meditsinskie-tsentry-i-apteki", "Медицинские центры и аптеки", CategoryEntityType.business, 80),
    ("ready-business", "ready-business-obrazovatelnye-tsentry", "Образовательные центры", CategoryEntityType.business, 90),
    ("ready-business", "ready-business-onlayn-magaziny", "Онлайн магазины", CategoryEntityType.business, 100),
    ("ready-business", "ready-business-franshizy", "Франшизы", CategoryEntityType.business, 110),
    ("ready-business", "ready-business-selskohozyaystvennyy-biznes", "Сельскохозяйственный бизнес", CategoryEntityType.business, 120),
    ("ready-business", "ready-business-razvlekatelnyy-biznes", "Развлекательный бизнес", CategoryEntityType.business, 130),
    ("ready-business", "ready-business-turisticheskiy-biznes", "Туристический бизнес", CategoryEntityType.business, 140),
    ("ready-business", "ready-business-finansovyy-investits-nyy-biznes", "Финансовый/инвестиц.ный бизнес", CategoryEntityType.business, 150),
    ("ready-business", "ready-business-kriptobiznes-i-tsifrovye-aktivy", "Криптобизнес и цифровые активы", CategoryEntityType.business, 160),
    ("ready-business", "ready-business-dolya-v-biznese-i-investitsii", "Доля в бизнесе и инвестиции", CategoryEntityType.business, 170),
    ("ready-business", "ready-business-biznes-pod-klyuch", "Бизнес под ключ", CategoryEntityType.business, 180),
    ("ready-business", "ready-business-prochiy-gotovyy-biznes", "Прочий готовый бизнес", CategoryEntityType.business, 190),
    ("home-garden", "home-garden-mebel-dlya-doma", "Мебель для дома", CategoryEntityType.object, 10),
    ("home-garden", "home-garden-mebel-dlya-sada-i-dachi", "Мебель для сада и дачи", CategoryEntityType.object, 20),
    ("home-garden", "home-garden-tekstil-i-kovry", "Текстиль и ковры", CategoryEntityType.object, 30),
    ("home-garden", "home-garden-shtory-zhalyuzi-i-karnizy", "Шторы, жалюзи и карнизы", CategoryEntityType.object, 40),
    ("home-garden", "home-garden-posuda-kuhonnye-prinadlezhnosti", "Посуда/кухонные принадлежности", CategoryEntityType.object, 50),
    ("home-garden", "home-garden-bytovaya-himiya-i-hoz-tovary", "Бытовая химия и хоз. товары", CategoryEntityType.object, 60),
    ("home-garden", "home-garden-hranenie-i-organizatsiya", "Хранение и организация", CategoryEntityType.object, 70),
    ("home-garden", "home-garden-osveschenie-i-elektrika-dlya-doma", "Освещение и электрика для дома", CategoryEntityType.object, 80),
    ("home-garden", "home-garden-dekor-i-interer", "Декор и интерьер", CategoryEntityType.object, 90),
    ("home-garden", "home-garden-komnatnye-rasteniya-i-tsvety", "Комнатные растения и цветы", CategoryEntityType.object, 100),
    ("home-garden", "home-garden-sazhentsy-i-rassada", "Саженцы и рассада", CategoryEntityType.object, 110),
    ("home-garden", "home-garden-semena-i-posadochnyy-material", "Семена и посадочный материал", CategoryEntityType.object, 120),
    ("home-garden", "home-garden-udobreniya-dlya-rasteniy", "Удобрения для растений", CategoryEntityType.object, 130),
    ("home-garden", "home-garden-sredstva-zaschity-rasteniy", "Средства защиты растений", CategoryEntityType.object, 140),
    ("home-garden", "home-garden-teplitsy-i-parniki", "Теплицы и парники", CategoryEntityType.object, 150),
    ("home-garden", "home-garden-poliv-i-oroshenie", "Полив и орошение", CategoryEntityType.object, 160),
    ("home-garden", "home-garden-sadovyy-inventar", "Садовый инвентарь", CategoryEntityType.object, 170),
    ("home-garden", "home-garden-sadovaya-tehnika", "Садовая техника", CategoryEntityType.object, 180),
    ("home-garden", "home-garden-besedki-navesy-i-tovary-dlya-dachi", "Беседки, навесы и товары для дачи", CategoryEntityType.object, 190),
    ("home-garden", "home-garden-mangaly-barbekyu-tandyr-grili", "Мангалы, барбекю, тандыр/грили", CategoryEntityType.object, 200),
    ("home-garden", "home-garden-basseyny-i-tovary-dlya-otdyha", "Бассейны и товары для отдыха", CategoryEntityType.object, 210),
    ("home-garden", "home-garden-tovary-dlya-bani-i-sauny", "Товары для бани и сауны", CategoryEntityType.object, 220),
    ("home-garden", "home-garden-prochee-dlya-doma-i-sada", "Прочее для дома и сада", CategoryEntityType.object, 230),
    ("stationery-books", "stationery-books-kantselyarskie-tovary", "Канцелярские товары", CategoryEntityType.object, 10),
    ("stationery-books", "stationery-books-uchebniki-i-uchebnye-posobiya", "Учебники и учебные пособия", CategoryEntityType.object, 20),
    ("stationery-books", "stationery-books-hudozhestvennaya-literatura", "Художественная литература", CategoryEntityType.object, 30),
    ("stationery-books", "stationery-books-nauchnaya-literatura", "Научная литература", CategoryEntityType.object, 40),
    ("stationery-books", "stationery-books-religioznaya-literatura", "Религиозная литература", CategoryEntityType.object, 50),
    ("stationery-books", "stationery-books-inostrannaya-literatura", "Иностранная литература", CategoryEntityType.object, 60),
    ("stationery-books", "stationery-books-elektronnye-knigi", "Электронные книги", CategoryEntityType.object, 70),
    ("stationery-books", "stationery-books-tovary-dlya-tvorchestva-risovaniya", "Товары для творчества/рисования", CategoryEntityType.object, 80),
    ("stationery-books", "stationery-books-tovary-dlya-ofisa", "Товары для офиса", CategoryEntityType.object, 90),
    ("stationery-books", "stationery-books-globusy-karty", "Глобусы, карты", CategoryEntityType.object, 100),
    ("stationery-books", "stationery-books-muzykalnye-knigi-i-noty", "Музыкальные книги и ноты", CategoryEntityType.object, 110),
    ("stationery-books", "stationery-books-komiksy-manga-grafich-e-romany", "Комиксы, манга/графич.е романы", CategoryEntityType.object, 120),
    ("stationery-books", "stationery-books-zhurnaly-i-periodicheskie-izdaniya", "Журналы и периодические издания", CategoryEntityType.object, 130),
    ("stationery-books", "stationery-books-kollektsionnye-i-redkie-izdaniya", "Коллекционные и редкие издания", CategoryEntityType.object, 140),
    ("stationery-books", "stationery-books-prochie-knigi-i-kantstovary", "Прочие книги и канцтовары", CategoryEntityType.object, 150),
    ("animals", "animals-ovtsy-barany-i-kozy", "Овцы, бараны и козы", CategoryEntityType.animal, 10),
    ("animals", "animals-korovy-byki-i-telyata", "Коровы, быки и телята", CategoryEntityType.animal, 20),
    ("animals", "animals-loshadi", "Лошади", CategoryEntityType.animal, 30),
    ("animals", "animals-ptitsevodstvo", "Птицеводство", CategoryEntityType.animal, 40),
    ("animals", "animals-sobaki", "Собаки", CategoryEntityType.animal, 50),
    ("animals", "animals-koshki", "Кошки", CategoryEntityType.animal, 60),
    ("animals", "animals-kroliki", "Кролики", CategoryEntityType.animal, 70),
    ("animals", "animals-pchelovodstvo", "Пчеловодство", CategoryEntityType.animal, 80),
    ("animals", "animals-ryby-i-akvariumistika", "Рыбы и аквариумистика", CategoryEntityType.animal, 90),
    ("animals", "animals-gryzuny", "Грызуны", CategoryEntityType.animal, 100),
    ("animals", "animals-reptilii-ekzoticheskie-zhivotnye", "Рептилии/экзотические животные", CategoryEntityType.animal, 110),
    ("animals", "animals-seno-korma-i-kormovye-dobavki", "Сено, Корма и кормовые добавки", CategoryEntityType.animal, 120),
    ("animals", "animals-tovary-aksessuary-dlya-zhivotnyh", "Товары/аксессуары для животных", CategoryEntityType.animal, 130),
    ("animals", "animals-vetapteka-i-veterinarnye-tovary", "Ветаптека и ветеринарные товары", CategoryEntityType.animal, 140),
    ("animals", "animals-veterinarnye-uslugi", "Ветеринарные услуги", CategoryEntityType.animal, 150),
    ("animals", "animals-prochie-zhivotnye", "Прочие животные", CategoryEntityType.animal, 160),
    ("sports-hobby", "sports-hobby-sportivnye-tovary", "Спортивные товары", CategoryEntityType.object, 10),
    ("sports-hobby", "sports-hobby-fitnes-i-trenazhery", "Фитнес и тренажёры", CategoryEntityType.object, 20),
    ("sports-hobby", "sports-hobby-sportivnoe-pitanie", "Спортивное питание", CategoryEntityType.object, 30),
    ("sports-hobby", "sports-hobby-turizm-i-kemping", "Туризм и кемпинг", CategoryEntityType.object, 40),
    ("sports-hobby", "sports-hobby-ohota-i-rybalka", "Охота и рыбалка", CategoryEntityType.object, 50),
    ("sports-hobby", "sports-hobby-muzykalnye-instrumenty", "Музыкальные инструменты", CategoryEntityType.object, 60),
    ("sports-hobby", "sports-hobby-kyrgyzskie-muzyk-nye-inst-menty", "Кыргызские музык.ные инст.менты", CategoryEntityType.object, 70),
    ("sports-hobby", "sports-hobby-yurty-i-natsionalnye-izdeliya", "Юрты и национальные изделия", CategoryEntityType.object, 80),
    ("sports-hobby", "sports-hobby-shyrdaki-i-izdeliya-iz-voyloka", "Шырдаки и изделия из войлока", CategoryEntityType.object, 90),
    ("sports-hobby", "sports-hobby-konnyy-sport-i-verhovaya-ezda", "Конный спорт и верховая езда", CategoryEntityType.object, 100),
    ("sports-hobby", "sports-hobby-kollektsionirovanie", "Коллекционирование", CategoryEntityType.object, 110),
    ("sports-hobby", "sports-hobby-nastolnye-igry", "Настольные игры", CategoryEntityType.object, 120),
    ("sports-hobby", "sports-hobby-rukodelie-i-tvorchestvo", "Рукоделие и творчество", CategoryEntityType.object, 130),
    ("sports-hobby", "sports-hobby-antikvariat-i-predmety-iskusstva", "Антиквариат и предметы искусства", CategoryEntityType.object, 140),
    ("sports-hobby", "sports-hobby-prochee-dlya-sporta-otdyha-i-hobbi", "Прочее для спорта, отдыха и хобби", CategoryEntityType.object, 150),
    ("materials", "materials-tkani-i-tekstilnoe-syre", "Ткани и текстильное сырьё", CategoryEntityType.raw_material, 10),
    ("materials", "materials-shveynaya-furnitura", "Швейная фурнитура", CategoryEntityType.raw_material, 20),
    ("materials", "materials-kozha-i-kozhzameniteli", "Кожа и кожзаменители", CategoryEntityType.raw_material, 30),
    ("materials", "materials-nitki-pryazha-i-volokno", "Нитки, пряжа и волокно", CategoryEntityType.raw_material, 40),
    ("materials", "materials-metally-metallicheskoe-syre", "Металлы/металлическое сырьё", CategoryEntityType.raw_material, 50),
    ("materials", "materials-drevesina-i-drevesnoe-syre", "Древесина и древесное сырьё", CategoryEntityType.raw_material, 60),
    ("materials", "materials-plastik-i-polimernoe-syre", "Пластик и полимерное сырьё", CategoryEntityType.raw_material, 70),
    ("materials", "materials-rezina-i-kauchuk", "Резина и каучук", CategoryEntityType.raw_material, 80),
    ("materials", "materials-bumaga-i-karton", "Бумага и картон", CategoryEntityType.raw_material, 90),
    ("materials", "materials-steklo-i-stekolnoe-syre", "Стекло и стекольное сырьё", CategoryEntityType.raw_material, 100),
    ("materials", "materials-himicheskoe-syre", "Химическое сырьё", CategoryEntityType.raw_material, 110),
    ("materials", "materials-lakokrasochnoe-syre", "Лакокрасочное сырьё", CategoryEntityType.raw_material, 120),
    ("materials", "materials-upakovochnye-materialy", "Упаковочные материалы", CategoryEntityType.raw_material, 130),
    ("materials", "materials-pischevoe-syre-i-ingredienty", "Пищевое сырьё и ингредиенты", CategoryEntityType.raw_material, 140),
    ("materials", "materials-syre-dlya-kosmetiki-parfyumerii", "Сырьё для косметики/парфюмерии", CategoryEntityType.raw_material, 150),
    ("materials", "materials-syre-dlya-bytovoy-himii", "Сырьё для бытовой химии", CategoryEntityType.raw_material, 160),
    ("materials", "materials-dlya-yuvelirnogo-proizvodstva", "Для ювелирного производства", CategoryEntityType.raw_material, 170),
    ("materials", "materials-import-i-optovye-postavki-syrya", "Импорт и оптовые поставки сырья", CategoryEntityType.raw_material, 180),
    ("materials", "materials-prochee-syre-dlya-proizvodstva", "Прочее сырьё для производства", CategoryEntityType.raw_material, 190),
]
