"""Mobile car brand/model catalog — generated from aivai_mobile Dart data.

Regenerate:
    python scripts/generate_vehicle_data_from_mobile.py
"""
from __future__ import annotations

MOBILE_POPULAR_BRAND_SLUGS: list[str] = ['toyota', 'mercedes-benz', 'bmw', 'lexus', 'honda', 'hyundai', 'kia', 'audi', 'nissan', 'volkswagen', 'geely', 'changan', 'haval', 'byd', 'zeekr']

MOBILE_VEHICLE_BRANDS: list[tuple[str, str]] = [
    ("abarth", "Abarth"),
    ("ac", "AC"),
    ("acura", "Acura"),
    ("aion", "Aion"),
    ("aito", "Aito"),
    ("aiways", "Aiways"),
    ("alfa-romeo", "Alfa Romeo"),
    ("alpine", "Alpine"),
    ("amc", "AMC"),
    ("arcfox", "Arcfox"),
    ("aston-martin", "Aston Martin"),
    ("audi", "Audi"),
    ("aurus", "Aurus"),
    ("avatr", "Avatr"),
    ("baic", "BAIC"),
    ("baw", "BAW"),
    ("bentley", "Bentley"),
    ("bmw", "BMW"),
    ("brilliance", "Brilliance"),
    ("bugatti", "Bugatti"),
    ("buick", "Buick"),
    ("byd", "BYD"),
    ("cadillac", "Cadillac"),
    ("caterham", "Caterham"),
    ("changan", "Changan"),
    ("chery", "Chery"),
    ("chevrolet", "Chevrolet"),
    ("chrysler", "Chrysler"),
    ("citroen", "Citroën"),
    ("cupra", "Cupra"),
    ("dacia", "Dacia"),
    ("daewoo", "Daewoo"),
    ("daihatsu", "Daihatsu"),
    ("datsun", "Datsun"),
    ("deepal", "Deepal"),
    ("denza", "Denza"),
    ("dfsk", "DFSK"),
    ("dodge", "Dodge"),
    ("dongfeng", "Dongfeng"),
    ("ds", "DS"),
    ("eagle", "Eagle"),
    ("exeed", "Exeed"),
    ("faw", "FAW"),
    ("ferrari", "Ferrari"),
    ("fiat", "Fiat"),
    ("fisker", "Fisker"),
    ("ford", "Ford"),
    ("forthing", "Forthing"),
    ("foton", "Foton"),
    ("gac", "GAC"),
    ("gaz", "GAZ"),
    ("geely", "Geely"),
    ("genesis", "Genesis"),
    ("geo", "Geo"),
    ("gmc", "GMC"),
    ("great-wall", "Great Wall"),
    ("haima", "Haima"),
    ("haval", "Haval"),
    ("hawtai", "Hawtai"),
    ("holden", "Holden"),
    ("honda", "Honda"),
    ("hongqi", "Hongqi"),
    ("hummer", "Hummer"),
    ("hycan", "Hycan"),
    ("hyundai", "Hyundai"),
    ("im", "IM"),
    ("infiniti", "Infiniti"),
    ("innocenti", "Innocenti"),
    ("isuzu", "Isuzu"),
    ("iveco", "Iveco"),
    ("jac", "JAC"),
    ("jaecoo", "Jaecoo"),
    ("jaguar", "Jaguar"),
    ("jeep", "Jeep"),
    ("jetour", "Jetour"),
    ("jetta", "Jetta"),
    ("kaiyi", "Kaiyi"),
    ("karma", "Karma"),
    ("kia", "KIA"),
    ("koenigsegg", "Koenigsegg"),
    ("lada", "Lada"),
    ("lamborghini", "Lamborghini"),
    ("lancia", "Lancia"),
    ("land-rover", "Land Rover"),
    ("leapmotor", "Leapmotor"),
    ("lexus", "Lexus"),
    ("li-auto", "Li Auto"),
    ("lifan", "Lifan"),
    ("lincoln", "Lincoln"),
    ("lotus", "Lotus"),
    ("lucid", "Lucid"),
    ("luxgen", "Luxgen"),
    ("lynk-co", "Lynk & Co"),
    ("maserati", "Maserati"),
    ("maxus", "Maxus"),
    ("maybach", "Maybach"),
    ("mazda", "Mazda"),
    ("mclaren", "McLaren"),
    ("mercedes-benz", "Mercedes-Benz"),
    ("mercury", "Mercury"),
    ("mg", "MG"),
    ("microcar", "Microcar"),
    ("mini", "Mini"),
    ("mitsubishi", "Mitsubishi"),
    ("mitsuoka", "Mitsuoka"),
    ("morgan", "Morgan"),
    ("moskvich", "Moskvich"),
    ("neta", "Neta"),
    ("nio", "Nio"),
    ("nissan", "Nissan"),
    ("oldsmobile", "Oldsmobile"),
    ("omoda", "Omoda"),
    ("opel", "Opel"),
    ("ora", "Ora"),
    ("pagani", "Pagani"),
    ("peugeot", "Peugeot"),
    ("plymouth", "Plymouth"),
    ("polestar", "Polestar"),
    ("pontiac", "Pontiac"),
    ("porsche", "Porsche"),
    ("proton", "Proton"),
    ("ram", "RAM"),
    ("ravon", "Ravon"),
    ("renault", "Renault"),
    ("renault-samsung", "Renault Samsung"),
    ("rimac", "Rimac"),
    ("rivian", "Rivian"),
    ("roewe", "Roewe"),
    ("rolls-royce", "Rolls-Royce"),
    ("rover", "Rover"),
    ("saab", "Saab"),
    ("saturn", "Saturn"),
    ("scion", "Scion"),
    ("seat", "SEAT"),
    ("seres", "Seres"),
    ("skoda", "Skoda"),
    ("smart", "Smart"),
    ("soueast", "Soueast"),
    ("ssangyong", "SsangYong"),
    ("subaru", "Subaru"),
    ("suzuki", "Suzuki"),
    ("tank", "Tank"),
    ("tata", "Tata"),
    ("tesla", "Tesla"),
    ("toyota", "Toyota"),
    ("tvr", "TVR"),
    ("uaz", "UAZ"),
    ("vauxhall", "Vauxhall"),
    ("venucia", "Venucia"),
    ("volkswagen", "Volkswagen"),
    ("volvo", "Volvo"),
    ("voyah", "Voyah"),
    ("weltmeister", "Weltmeister"),
    ("wey", "Wey"),
    ("wuling", "Wuling"),
    ("xpeng", "XPeng"),
    ("yangwang", "Yangwang"),
    ("zeekr", "Zeekr"),
    ("zotye", "Zotye"),
    ("zx", "ZX"),
]

MOBILE_VEHICLE_MODELS: dict[str, list[tuple[str, str]]] = {
    "abarth": [
        ("124-spider", "124 Spider"),
        ("500", "500"),
        ("595", "595"),
        ("695", "695"),
        ("grande-punto", "Grande Punto"),
        ("punto", "Punto"),
    ],
    "ac": [
        ("378-gt", "378 GT"),
        ("ace", "Ace"),
        ("aceca", "Aceca"),
        ("cobra", "Cobra"),
        ("gt", "GT"),
    ],
    "acura": [
        ("ilx", "ILX"),
        ("integra", "Integra"),
        ("mdx", "MDX"),
        ("nsx", "NSX"),
        ("rdx", "RDX"),
        ("rlx", "RLX"),
        ("tl", "TL"),
        ("tlx", "TLX"),
        ("tsx", "TSX"),
        ("zdx", "ZDX"),
    ],
    "aion": [
        ("aion-hyper-gt", "Aion Hyper GT"),
        ("aion-hyper-ht", "Aion Hyper HT"),
        ("aion-hyper-ssr", "Aion Hyper SSR"),
        ("aion-lx", "Aion LX"),
        ("aion-s", "Aion S"),
        ("aion-v", "Aion V"),
        ("aion-y", "Aion Y"),
        ("es", "ES"),
        ("lx-plus", "LX Plus"),
        ("rt", "RT"),
        ("s-plus", "S Plus"),
        ("ut", "UT"),
    ],
    "aito": [
        ("m5", "M5"),
        ("m7", "M7"),
        ("m8", "M8"),
        ("m9", "M9"),
    ],
    "aiways": [
        ("u5", "U5"),
        ("u6", "U6"),
        ("u7", "U7"),
    ],
    "alfa-romeo": [
        ("145", "145"),
        ("146", "146"),
        ("147", "147"),
        ("156", "156"),
        ("159", "159"),
        ("166", "166"),
        ("4c", "4C"),
        ("8c", "8C"),
        ("brera", "Brera"),
        ("giulia", "Giulia"),
        ("giulietta", "Giulietta"),
        ("gt", "GT"),
        ("gtv", "GTV"),
        ("mito", "MiTo"),
        ("spider", "Spider"),
        ("stelvio", "Stelvio"),
        ("tonale", "Tonale"),
    ],
    "alpine": [
        ("a110", "A110"),
        ("a290", "A290"),
        ("a310", "A310"),
        ("a610", "A610"),
    ],
    "amc": [
        ("ambassador", "Ambassador"),
        ("concord", "Concord"),
        ("eagle", "Eagle"),
        ("gremlin", "Gremlin"),
        ("hornet", "Hornet"),
        ("javelin", "Javelin"),
        ("matador", "Matador"),
        ("pacer", "Pacer"),
        ("spirit", "Spirit"),
    ],
    "arcfox": [
        ("alpha-s", "Alpha S"),
        ("alpha-t", "Alpha T"),
        ("kaola", "Kaola"),
        ("lite", "Lite"),
    ],
    "aston-martin": [
        ("db11", "DB11"),
        ("db12", "DB12"),
        ("db7", "DB7"),
        ("db9", "DB9"),
        ("dbs", "DBS"),
        ("dbx", "DBX"),
        ("rapide", "Rapide"),
        ("v12-vantage", "V12 Vantage"),
        ("v8-vantage", "V8 Vantage"),
        ("vanquish", "Vanquish"),
        ("virage", "Virage"),
    ],
    "audi": [
        ("100", "100"),
        ("80", "80"),
        ("90", "90"),
        ("a1", "A1"),
        ("a3", "A3"),
        ("a4", "A4"),
        ("a5", "A5"),
        ("a6", "A6"),
        ("a7", "A7"),
        ("a8", "A8"),
        ("e-tron", "e-tron"),
        ("e-tron-gt", "e-tron GT"),
        ("q2", "Q2"),
        ("q3", "Q3"),
        ("q4", "Q4"),
        ("q5", "Q5"),
        ("q7", "Q7"),
        ("q8", "Q8"),
        ("r8", "R8"),
        ("rs3", "RS3"),
        ("rs4", "RS4"),
        ("rs5", "RS5"),
        ("rs6", "RS6"),
        ("rs7", "RS7"),
        ("s3", "S3"),
        ("s4", "S4"),
        ("s5", "S5"),
        ("s6", "S6"),
        ("s8", "S8"),
        ("tt", "TT"),
    ],
    "aurus": [
        ("komendant", "Komendant"),
        ("senat", "Senat"),
    ],
    "avatr": [
        ("06", "06"),
        ("07", "07"),
        ("11", "11"),
        ("12", "12"),
    ],
    "baic": [
        ("bj20", "BJ20"),
        ("bj30", "BJ30"),
        ("bj40", "BJ40"),
        ("bj60", "BJ60"),
        ("bj80", "BJ80"),
        ("bj90", "BJ90"),
        ("eu5", "EU5"),
        ("eu7", "EU7"),
        ("senova-d50", "Senova D50"),
        ("senova-d70", "Senova D70"),
        ("senova-x25", "Senova X25"),
        ("senova-x35", "Senova X35"),
        ("senova-x55", "Senova X55"),
        ("senova-x65", "Senova X65"),
        ("x25", "X25"),
        ("x35", "X35"),
        ("x55", "X55"),
        ("x75", "X75"),
    ],
    "baw": [
        ("212", "212"),
        ("bj30", "BJ30"),
        ("bj60", "BJ60"),
        ("warrior", "Warrior"),
    ],
    "bentley": [
        ("arnage", "Arnage"),
        ("azure", "Azure"),
        ("bentayga", "Bentayga"),
        ("brooklands", "Brooklands"),
        ("continental", "Continental"),
        ("flying-spur", "Flying Spur"),
        ("mulsanne", "Mulsanne"),
    ],
    "bmw": [
        ("1-series", "1 Series"),
        ("2-series", "2 Series"),
        ("3-series", "3 Series"),
        ("4-series", "4 Series"),
        ("5-series", "5 Series"),
        ("6-series", "6 Series"),
        ("7-series", "7 Series"),
        ("8-series", "8 Series"),
        ("i3", "i3"),
        ("i4", "i4"),
        ("i5", "i5"),
        ("i7", "i7"),
        ("i8", "i8"),
        ("ix", "iX"),
        ("ix1", "iX1"),
        ("ix3", "iX3"),
        ("m2", "M2"),
        ("m3", "M3"),
        ("m4", "M4"),
        ("m5", "M5"),
        ("m6", "M6"),
        ("m8", "M8"),
        ("x1", "X1"),
        ("x2", "X2"),
        ("x3", "X3"),
        ("x4", "X4"),
        ("x5", "X5"),
        ("x6", "X6"),
        ("x7", "X7"),
        ("xm", "XM"),
        ("z3", "Z3"),
        ("z4", "Z4"),
        ("z8", "Z8"),
    ],
    "brilliance": [
        ("frv", "FRV"),
        ("fsv", "FSV"),
        ("h220", "H220"),
        ("h230", "H230"),
        ("h320", "H320"),
        ("h330", "H330"),
        ("h420", "H420"),
        ("h530", "H530"),
        ("v3", "V3"),
        ("v5", "V5"),
        ("v6", "V6"),
        ("v7", "V7"),
    ],
    "bugatti": [
        ("chiron", "Chiron"),
        ("divo", "Divo"),
        ("eb110", "EB110"),
        ("veyron", "Veyron"),
    ],
    "buick": [
        ("cascada", "Cascada"),
        ("century", "Century"),
        ("electra", "Electra"),
        ("enclave", "Enclave"),
        ("encore", "Encore"),
        ("encore-gx", "Encore GX"),
        ("envision", "Envision"),
        ("envista", "Envista"),
        ("lacrosse", "LaCrosse"),
        ("lesabre", "LeSabre"),
        ("lucerne", "Lucerne"),
        ("park-avenue", "Park Avenue"),
        ("rainier", "Rainier"),
        ("regal", "Regal"),
        ("rendezvous", "Rendezvous"),
        ("riviera", "Riviera"),
        ("roadmaster", "Roadmaster"),
        ("skylark", "Skylark"),
        ("terraza", "Terraza"),
        ("verano", "Verano"),
        ("wildcat", "Wildcat"),
    ],
    "byd": [
        ("atto-2", "Atto 2"),
        ("atto-2-dm-i", "Atto 2 DM-i"),
        ("atto-3", "Atto 3"),
        ("atto-3-evo", "Atto 3 EVO"),
        ("destroyer-05", "Destroyer 05"),
        ("dolphin", "Dolphin"),
        ("dolphin-mini", "Dolphin Mini"),
        ("dolphin-surf", "Dolphin Surf"),
        ("e2", "e2"),
        ("e3", "e3"),
        ("e5", "e5"),
        ("e6", "e6"),
        ("f0", "F0"),
        ("f3", "F3"),
        ("f6", "F6"),
        ("frigate-07", "Frigate 07"),
        ("g3", "G3"),
        ("g5", "G5"),
        ("han", "Han"),
        ("l3", "L3"),
        ("m6", "M6"),
        ("qin", "Qin"),
        ("qin-l", "Qin L"),
        ("qin-plus", "Qin Plus"),
        ("s6", "S6"),
        ("s7", "S7"),
        ("seagull", "Seagull"),
        ("seal", "Seal"),
        ("seal-6-dm-i", "Seal 6 DM-i"),
        ("seal-6-dm-i-touring", "Seal 6 DM-i Touring"),
        ("seal-u", "Seal U"),
        ("seal-u-dm-i", "Seal U DM-i"),
        ("sealion-5-dm-i", "Sealion 5 DM-i"),
        ("sealion-6", "Sealion 6"),
        ("sealion-7", "Sealion 7"),
        ("shark", "Shark"),
        ("song", "Song"),
        ("song-l", "Song L"),
        ("song-max", "Song Max"),
        ("song-plus", "Song Plus"),
        ("song-pro", "Song Pro"),
        ("tang", "Tang"),
        ("yuan", "Yuan"),
        ("yuan-plus", "Yuan Plus"),
        ("yuan-pro", "Yuan Pro"),
    ],
    "cadillac": [
        ("allante", "Allante"),
        ("ats", "ATS"),
        ("bls", "BLS"),
        ("catera", "Catera"),
        ("celestiq", "Celestiq"),
        ("ct4", "CT4"),
        ("ct5", "CT5"),
        ("ct6", "CT6"),
        ("cts", "CTS"),
        ("deville", "DeVille"),
        ("dts", "DTS"),
        ("eldorado", "Eldorado"),
        ("escalade", "Escalade"),
        ("fleetwood", "Fleetwood"),
        ("lyriq", "Lyriq"),
        ("seville", "Seville"),
        ("srx", "SRX"),
        ("sts", "STS"),
        ("xt4", "XT4"),
        ("xt5", "XT5"),
        ("xt6", "XT6"),
        ("xts", "XTS"),
    ],
    "caterham": [
        ("seven", "Seven"),
        ("seven-160", "Seven 160"),
        ("seven-270", "Seven 270"),
        ("seven-310", "Seven 310"),
        ("seven-420", "Seven 420"),
        ("seven-620", "Seven 620"),
    ],
    "changan": [
        ("alsvin", "Alsvin"),
        ("benben", "BenBen"),
        ("cs15", "CS15"),
        ("cs35", "CS35"),
        ("cs35-max", "CS35 Max"),
        ("cs35-plus", "CS35 Plus"),
        ("cs55", "CS55"),
        ("cs55-plus", "CS55 Plus"),
        ("cs75", "CS75"),
        ("cs75-plus", "CS75 Plus"),
        ("cs75-pro", "CS75 Pro"),
        ("cs85", "CS85"),
        ("cs95", "CS95"),
        ("cs95-plus", "CS95 Plus"),
        ("e-star", "E-Star"),
        ("eado", "Eado"),
        ("eado-plus", "Eado Plus"),
        ("hunter", "Hunter"),
        ("hunter-plus", "Hunter Plus"),
        ("lamore", "Lamore"),
        ("lumin", "Lumin"),
        ("qiyuan-a05", "Qiyuan A05"),
        ("qiyuan-a06", "Qiyuan A06"),
        ("qiyuan-a07", "Qiyuan A07"),
        ("qiyuan-e07", "Qiyuan E07"),
        ("qiyuan-q05", "Qiyuan Q05"),
        ("raeton", "Raeton"),
        ("uni-k", "UNI-K"),
        ("uni-s", "UNI-S"),
        ("uni-t", "UNI-T"),
        ("uni-v", "UNI-V"),
        ("uni-z", "UNI-Z"),
        ("x5-plus", "X5 Plus"),
    ],
    "chery": [
        ("arrizo-3", "Arrizo 3"),
        ("arrizo-5", "Arrizo 5"),
        ("arrizo-6", "Arrizo 6"),
        ("arrizo-7", "Arrizo 7"),
        ("arrizo-8", "Arrizo 8"),
        ("bonus", "Bonus"),
        ("eq1", "eQ1"),
        ("eq5", "eQ5"),
        ("fora", "Fora"),
        ("fulwin", "Fulwin"),
        ("qq", "QQ"),
        ("tiggo-2", "Tiggo 2"),
        ("tiggo-3", "Tiggo 3"),
        ("tiggo-4", "Tiggo 4"),
        ("tiggo-4-pro", "Tiggo 4 Pro"),
        ("tiggo-5", "Tiggo 5"),
        ("tiggo-7", "Tiggo 7"),
        ("tiggo-7-pro", "Tiggo 7 Pro"),
        ("tiggo-7-pro-max", "Tiggo 7 Pro Max"),
        ("tiggo-8", "Tiggo 8"),
        ("tiggo-8-pro", "Tiggo 8 Pro"),
        ("tiggo-8-pro-max", "Tiggo 8 Pro Max"),
        ("tiggo-9", "Tiggo 9"),
        ("very", "Very"),
        ("windcloud", "Windcloud"),
    ],
    "chevrolet": [
        ("aveo", "Aveo"),
        ("blazer", "Blazer"),
        ("bolt", "Bolt"),
        ("bolt-euv", "Bolt EUV"),
        ("camaro", "Camaro"),
        ("caprice", "Caprice"),
        ("captiva", "Captiva"),
        ("celta", "Celta"),
        ("cobalt", "Cobalt"),
        ("colorado", "Colorado"),
        ("corvette", "Corvette"),
        ("cruze", "Cruze"),
        ("epica", "Epica"),
        ("equinox", "Equinox"),
        ("express", "Express"),
        ("hhr", "HHR"),
        ("impala", "Impala"),
        ("lacetti", "Lacetti"),
        ("lumina", "Lumina"),
        ("malibu", "Malibu"),
        ("monte-carlo", "Monte Carlo"),
        ("monza", "Monza"),
        ("niva", "Niva"),
        ("onix", "Onix"),
        ("orlando", "Orlando"),
        ("prizm", "Prizm"),
        ("s10", "S10"),
        ("silverado", "Silverado"),
        ("spark", "Spark"),
        ("spin", "Spin"),
        ("ssr", "SSR"),
        ("suburban", "Suburban"),
        ("tahoe", "Tahoe"),
        ("tracker", "Tracker"),
        ("trailblazer", "TrailBlazer"),
        ("traverse", "Traverse"),
        ("trax", "Trax"),
        ("uplander", "Uplander"),
        ("volt", "Volt"),
    ],
    "chrysler": [
        ("200", "200"),
        ("300", "300"),
        ("300c", "300C"),
        ("300m", "300M"),
        ("crossfire", "Crossfire"),
        ("grand-voyager", "Grand Voyager"),
        ("lebaron", "LeBaron"),
        ("neon", "Neon"),
        ("pacifica", "Pacifica"),
        ("pt-cruiser", "PT Cruiser"),
        ("sebring", "Sebring"),
        ("town-country", "Town & Country"),
        ("voyager", "Voyager"),
    ],
    "citroen": [
        ("berlingo", "Berlingo"),
        ("c-crosser", "C-Crosser"),
        ("c-elysee", "C-Elysee"),
        ("c1", "C1"),
        ("c2", "C2"),
        ("c3", "C3"),
        ("c4", "C4"),
        ("c5", "C5"),
        ("c6", "C6"),
        ("c8", "C8"),
        ("ds3", "DS3"),
        ("ds4", "DS4"),
        ("ds5", "DS5"),
        ("jumper", "Jumper"),
        ("jumpy", "Jumpy"),
        ("nemo", "Nemo"),
        ("saxo", "Saxo"),
        ("spacetourer", "SpaceTourer"),
        ("xantia", "Xantia"),
        ("xsara", "Xsara"),
        ("xsara-picasso", "Xsara Picasso"),
    ],
    "cupra": [
        ("ateca", "Ateca"),
        ("born", "Born"),
        ("formentor", "Formentor"),
        ("leon", "Leon"),
        ("tavascan", "Tavascan"),
        ("terramar", "Terramar"),
    ],
    "dacia": [
        ("bigster", "Bigster"),
        ("dokker", "Dokker"),
        ("duster", "Duster"),
        ("jogger", "Jogger"),
        ("lodgy", "Lodgy"),
        ("logan", "Logan"),
        ("logan-mcv", "Logan MCV"),
        ("sandero", "Sandero"),
        ("solenza", "Solenza"),
        ("spring", "Spring"),
    ],
    "daewoo": [
        ("damas", "Damas"),
        ("espero", "Espero"),
        ("evanda", "Evanda"),
        ("gentra", "Gentra"),
        ("kalos", "Kalos"),
        ("lacetti", "Lacetti"),
        ("lanos", "Lanos"),
        ("leganza", "Leganza"),
        ("magnus", "Magnus"),
        ("matiz", "Matiz"),
        ("nexia", "Nexia"),
        ("nubira", "Nubira"),
        ("sens", "Sens"),
        ("tacuma", "Tacuma"),
        ("tico", "Tico"),
    ],
    "daihatsu": [
        ("applause", "Applause"),
        ("charade", "Charade"),
        ("copen", "Copen"),
        ("cuore", "Cuore"),
        ("feroza", "Feroza"),
        ("gran-move", "Gran Move"),
        ("materia", "Materia"),
        ("move", "Move"),
        ("rocky", "Rocky"),
        ("sirion", "Sirion"),
        ("terios", "Terios"),
        ("yrv", "YRV"),
    ],
    "datsun": [
        ("mi-do", "mi-DO"),
        ("on-do", "on-DO"),
    ],
    "deepal": [
        ("g318", "G318"),
        ("l07", "L07"),
        ("s05", "S05"),
        ("s07", "S07"),
        ("sl03", "SL03"),
    ],
    "denza": [
        ("d9", "D9"),
        ("n7", "N7"),
        ("n8", "N8"),
        ("x", "X"),
        ("z9", "Z9"),
        ("z9-gt", "Z9 GT"),
    ],
    "dfsk": [
        ("c31", "C31"),
        ("c32", "C32"),
        ("c35", "C35"),
        ("c51", "C51"),
        ("c52", "C52"),
        ("c56", "C56"),
        ("c71", "C71"),
        ("c72", "C72"),
        ("e5", "E5"),
        ("fengon-5", "Fengon 5"),
        ("fengon-7", "Fengon 7"),
        ("glory-330", "Glory 330"),
        ("glory-500", "Glory 500"),
        ("glory-580", "Glory 580"),
        ("ix5", "iX5"),
        ("ix7", "iX7"),
        ("k01", "K01"),
        ("k02", "K02"),
        ("k05", "K05"),
        ("k07", "K07"),
    ],
    "dodge": [
        ("avenger", "Avenger"),
        ("caliber", "Caliber"),
        ("caravan", "Caravan"),
        ("challenger", "Challenger"),
        ("charger", "Charger"),
        ("coronet", "Coronet"),
        ("dakota", "Dakota"),
        ("dart", "Dart"),
        ("daytona", "Daytona"),
        ("durango", "Durango"),
        ("grand-caravan", "Grand Caravan"),
        ("hornet", "Hornet"),
        ("intrepid", "Intrepid"),
        ("journey", "Journey"),
        ("magnum", "Magnum"),
        ("monaco", "Monaco"),
        ("neon", "Neon"),
        ("nitro", "Nitro"),
        ("omni", "Omni"),
        ("ram", "Ram"),
        ("shadow", "Shadow"),
        ("spirit", "Spirit"),
        ("stealth", "Stealth"),
        ("stratus", "Stratus"),
        ("viper", "Viper"),
    ],
    "dongfeng": [
        ("580", "580"),
        ("a30", "A30"),
        ("aeolus-a60", "Aeolus A60"),
        ("aeolus-ax7", "Aeolus AX7"),
        ("aeolus-e70", "Aeolus E70"),
        ("aeolus-yixuan", "Aeolus Yixuan"),
        ("aeolus-yixuan-gs", "Aeolus Yixuan GS"),
        ("ax7", "AX7"),
        ("h30", "H30"),
        ("mx3", "MX3"),
        ("nammi", "Nammi"),
        ("rich", "Rich"),
        ("s30", "S30"),
        ("shine", "Shine"),
        ("t5-evo", "T5 EVO"),
    ],
    "ds": [
        ("3", "3"),
        ("4", "4"),
        ("5", "5"),
        ("7", "7"),
        ("9", "9"),
    ],
    "eagle": [
        ("premier", "Premier"),
        ("summit", "Summit"),
        ("talon", "Talon"),
        ("vision", "Vision"),
    ],
    "exeed": [
        ("lx", "LX"),
        ("rx", "RX"),
        ("sterra-es", "Sterra ES"),
        ("sterra-et", "Sterra ET"),
        ("tx", "TX"),
        ("txl", "TXL"),
        ("vx", "VX"),
    ],
    "faw": [
        ("bestune-b70", "Bestune B70"),
        ("bestune-b70s", "Bestune B70S"),
        ("bestune-e01", "Bestune E01"),
        ("bestune-m9", "Bestune M9"),
        ("bestune-nat", "Bestune NAT"),
        ("bestune-pony", "Bestune Pony"),
        ("bestune-t55", "Bestune T55"),
        ("bestune-t77", "Bestune T77"),
        ("bestune-t90", "Bestune T90"),
        ("bestune-t99", "Bestune T99"),
        ("hongqi-h5", "Hongqi H5"),
        ("hongqi-h9", "Hongqi H9"),
        ("v2", "V2"),
        ("v5", "V5"),
        ("vita", "Vita"),
    ],
    "ferrari": [
        ("296", "296"),
        ("308", "308"),
        ("328", "328"),
        ("348", "348"),
        ("360", "360"),
        ("456", "456"),
        ("458", "458"),
        ("488", "488"),
        ("512", "512"),
        ("550", "550"),
        ("575", "575"),
        ("599", "599"),
        ("612", "612"),
        ("812", "812"),
        ("california", "California"),
        ("enzo", "Enzo"),
        ("f12", "F12"),
        ("f355", "F355"),
        ("f40", "F40"),
        ("f430", "F430"),
        ("f8", "F8"),
        ("ff", "FF"),
        ("gtc4lusso", "GTC4Lusso"),
        ("laferrari", "LaFerrari"),
        ("mondial", "Mondial"),
        ("portofino", "Portofino"),
        ("purosangue", "Purosangue"),
        ("roma", "Roma"),
        ("sf90", "SF90"),
        ("testarossa", "Testarossa"),
    ],
    "fiat": [
        ("124-spider", "124 Spider"),
        ("500", "500"),
        ("500l", "500L"),
        ("500x", "500X"),
        ("albea", "Albea"),
        ("barchetta", "Barchetta"),
        ("brava", "Brava"),
        ("bravo", "Bravo"),
        ("croma", "Croma"),
        ("doblo", "Doblo"),
        ("ducato", "Ducato"),
        ("fiorino", "Fiorino"),
        ("freemont", "Freemont"),
        ("fullback", "Fullback"),
        ("linea", "Linea"),
        ("marea", "Marea"),
        ("multipla", "Multipla"),
        ("palio", "Palio"),
        ("panda", "Panda"),
        ("punto", "Punto"),
        ("qubo", "Qubo"),
        ("scudo", "Scudo"),
        ("sedici", "Sedici"),
        ("seicento", "Seicento"),
        ("stilo", "Stilo"),
        ("tipo", "Tipo"),
        ("ulysse", "Ulysse"),
        ("uno", "Uno"),
    ],
    "fisker": [
        ("karma", "Karma"),
        ("ocean", "Ocean"),
        ("pear", "Pear"),
    ],
    "ford": [
        ("bronco", "Bronco"),
        ("bronco-sport", "Bronco Sport"),
        ("c-max", "C-Max"),
        ("capri", "Capri"),
        ("ecosport", "EcoSport"),
        ("edge", "Edge"),
        ("escape", "Escape"),
        ("everest", "Everest"),
        ("expedition", "Expedition"),
        ("explorer", "Explorer"),
        ("f-150", "F-150"),
        ("fairlane", "Fairlane"),
        ("falcon", "Falcon"),
        ("festiva", "Festiva"),
        ("fiesta", "Fiesta"),
        ("flex", "Flex"),
        ("focus", "Focus"),
        ("freestar", "Freestar"),
        ("fusion", "Fusion"),
        ("galaxy", "Galaxy"),
        ("ka", "Ka"),
        ("kuga", "Kuga"),
        ("laser", "Laser"),
        ("ltd", "LTD"),
        ("maverick", "Maverick"),
        ("mondeo", "Mondeo"),
        ("mustang", "Mustang"),
        ("mustang-mach-e", "Mustang Mach-E"),
        ("probe", "Probe"),
        ("puma", "Puma"),
        ("ranger", "Ranger"),
        ("s-max", "S-Max"),
        ("scorpio", "Scorpio"),
        ("sierra", "Sierra"),
        ("taurus", "Taurus"),
        ("telstar", "Telstar"),
        ("territory", "Territory"),
        ("thunderbird", "Thunderbird"),
        ("tourneo", "Tourneo"),
        ("transit", "Transit"),
        ("windstar", "Windstar"),
    ],
    "forthing": [
        ("friday", "Friday"),
        ("mango", "Mango"),
        ("t5-evo", "T5 EVO"),
        ("u-tour", "U-Tour"),
        ("v9", "V9"),
        ("yacht", "Yacht"),
    ],
    "foton": [
        ("sauvana", "Sauvana"),
        ("tunland", "Tunland"),
        ("view", "View"),
    ],
    "gac": [
        ("aion-es", "Aion ES"),
        ("aion-hyper-gt", "Aion Hyper GT"),
        ("aion-hyper-ht", "Aion Hyper HT"),
        ("aion-hyper-ssr", "Aion Hyper SSR"),
        ("aion-lx", "Aion LX"),
        ("aion-s", "Aion S"),
        ("aion-v", "Aion V"),
        ("aion-y", "Aion Y"),
        ("empow", "Empow"),
        ("ga3", "GA3"),
        ("ga4", "GA4"),
        ("ga5", "GA5"),
        ("ga6", "GA6"),
        ("ga8", "GA8"),
        ("gn8", "GN8"),
        ("gs3", "GS3"),
        ("gs4", "GS4"),
        ("gs4-coupe", "GS4 Coupe"),
        ("gs5", "GS5"),
        ("gs7", "GS7"),
        ("gs8", "GS8"),
        ("m6", "M6"),
        ("m8", "M8"),
        ("trumpchi-e9", "Trumpchi E9"),
        ("trumpchi-es9", "Trumpchi ES9"),
        ("trumpchi-m8", "Trumpchi M8"),
    ],
    "gaz": [
        ("21", "21"),
        ("24", "24"),
        ("3102", "3102"),
        ("3110", "3110"),
        ("3111", "3111"),
        ("gazelle", "Gazelle"),
        ("sobol", "Sobol"),
        ("volga", "Volga"),
    ],
    "geely": [
        ("atlas", "Atlas"),
        ("atlas-pro", "Atlas Pro"),
        ("azkarra", "Azkarra"),
        ("binrui", "Binrui"),
        ("borui", "Borui"),
        ("boyue", "Boyue"),
        ("boyue-l", "Boyue L"),
        ("cityray", "Cityray"),
        ("ck", "CK"),
        ("coolray", "Coolray"),
        ("cowboy", "Cowboy"),
        ("emgrand", "Emgrand"),
        ("emgrand-ec7", "Emgrand EC7"),
        ("fc", "FC"),
        ("galaxy-e5", "Galaxy E5"),
        ("galaxy-e8", "Galaxy E8"),
        ("galaxy-l6", "Galaxy L6"),
        ("galaxy-l7", "Galaxy L7"),
        ("galaxy-starship-7", "Galaxy Starship 7"),
        ("geometry-a", "Geometry A"),
        ("geometry-c", "Geometry C"),
        ("geometry-e", "Geometry E"),
        ("geometry-m6", "Geometry M6"),
        ("haoyue", "Haoyue"),
        ("icon", "Icon"),
        ("jiaji", "Jiaji"),
        ("mk", "MK"),
        ("monjaro", "Monjaro"),
        ("okavango", "Okavango"),
        ("panda-mini", "Panda Mini"),
        ("preface", "Preface"),
        ("tugella", "Tugella"),
        ("vision", "Vision"),
        ("xingrui", "Xingrui"),
        ("xingyue", "Xingyue"),
        ("xingyue-l", "Xingyue L"),
    ],
    "genesis": [
        ("coupe", "Coupe"),
        ("g70", "G70"),
        ("g80", "G80"),
        ("g90", "G90"),
        ("gv60", "GV60"),
        ("gv70", "GV70"),
        ("gv80", "GV80"),
        ("gv90", "GV90"),
    ],
    "geo": [
        ("metro", "Metro"),
        ("prizm", "Prizm"),
        ("spectrum", "Spectrum"),
        ("storm", "Storm"),
        ("tracker", "Tracker"),
    ],
    "gmc": [
        ("acadia", "Acadia"),
        ("canyon", "Canyon"),
        ("envoy", "Envoy"),
        ("hummer-ev", "Hummer EV"),
        ("jimmy", "Jimmy"),
        ("safari", "Safari"),
        ("savana", "Savana"),
        ("sierra", "Sierra"),
        ("sonoma", "Sonoma"),
        ("syclone", "Syclone"),
        ("terrain", "Terrain"),
        ("typhoon", "Typhoon"),
        ("vandura", "Vandura"),
        ("yukon", "Yukon"),
    ],
    "great-wall": [
        ("c30", "C30"),
        ("c50", "C50"),
        ("cannon", "Cannon"),
        ("deer", "Deer"),
        ("florid", "Florid"),
        ("h3", "H3"),
        ("h5", "H5"),
        ("h6", "H6"),
        ("hover", "Hover"),
        ("m2", "M2"),
        ("m4", "M4"),
        ("peri", "Peri"),
        ("poer", "Poer"),
        ("safe", "Safe"),
        ("sailor", "Sailor"),
        ("wingle", "Wingle"),
    ],
    "haima": [
        ("2", "2"),
        ("3", "3"),
        ("7x", "7X"),
        ("8s", "8S"),
        ("family", "Family"),
        ("freema", "Freema"),
        ("m3", "M3"),
        ("s5", "S5"),
        ("s7", "S7"),
    ],
    "haval": [
        ("big-dog", "Big Dog"),
        ("cool-dog", "Cool Dog"),
        ("dargo", "Dargo"),
        ("f7", "F7"),
        ("f7x", "F7x"),
        ("h2", "H2"),
        ("h3", "H3"),
        ("h5", "H5"),
        ("h6", "H6"),
        ("h6-coupe", "H6 Coupe"),
        ("h8", "H8"),
        ("h9", "H9"),
        ("jolion", "Jolion"),
        ("m6", "M6"),
        ("raptor", "Raptor"),
        ("shenshou", "Shenshou"),
    ],
    "hawtai": [
        ("a25", "A25"),
        ("b11", "B11"),
        ("boliger", "Boliger"),
        ("laville", "Laville"),
    ],
    "holden": [
        ("astra", "Astra"),
        ("barina", "Barina"),
        ("calais", "Calais"),
        ("caprice", "Caprice"),
        ("colorado", "Colorado"),
        ("commodore", "Commodore"),
        ("cruze", "Cruze"),
        ("epica", "Epica"),
        ("jackaroo", "Jackaroo"),
        ("monaro", "Monaro"),
        ("rodeo", "Rodeo"),
        ("statesman", "Statesman"),
        ("ute", "Ute"),
        ("vectra", "Vectra"),
    ],
    "honda": [
        ("accord", "Accord"),
        ("amaze", "Amaze"),
        ("br-v", "BR-V"),
        ("brio", "Brio"),
        ("city", "City"),
        ("civic", "Civic"),
        ("cr-v", "CR-V"),
        ("cr-z", "CR-Z"),
        ("crosstour", "Crosstour"),
        ("e", "e"),
        ("e-np1", "e:NP1"),
        ("e-ns1", "e:NS1"),
        ("element", "Element"),
        ("elevate", "Elevate"),
        ("elysion", "Elysion"),
        ("fit", "Fit"),
        ("fr-v", "FR-V"),
        ("freed", "Freed"),
        ("hr-v", "HR-V"),
        ("insight", "Insight"),
        ("integra", "Integra"),
        ("jazz", "Jazz"),
        ("lagreat", "Lagreat"),
        ("legend", "Legend"),
        ("mobilio", "Mobilio"),
        ("nsx", "NSX"),
        ("odyssey", "Odyssey"),
        ("passport", "Passport"),
        ("pilot", "Pilot"),
        ("prelude", "Prelude"),
        ("ridgeline", "Ridgeline"),
        ("s2000", "S2000"),
        ("shuttle", "Shuttle"),
        ("stepwgn", "Stepwgn"),
        ("stream", "Stream"),
        ("vezel", "Vezel"),
        ("wr-v", "WR-V"),
        ("zr-v", "ZR-V"),
    ],
    "hongqi": [
        ("e-hs3", "E-HS3"),
        ("e-hs9", "E-HS9"),
        ("e-qm5", "E-QM5"),
        ("eh7", "EH7"),
        ("h5", "H5"),
        ("h6", "H6"),
        ("h7", "H7"),
        ("h9", "H9"),
        ("hq9", "HQ9"),
        ("hs3", "HS3"),
        ("hs5", "HS5"),
        ("hs7", "HS7"),
        ("l5", "L5"),
        ("ls7", "LS7"),
    ],
    "hummer": [
        ("ev", "EV"),
        ("h1", "H1"),
        ("h2", "H2"),
        ("h3", "H3"),
    ],
    "hycan": [
        ("007", "007"),
        ("a06", "A06"),
        ("z03", "Z03"),
    ],
    "hyundai": [
        ("accent", "Accent"),
        ("atos", "Atos"),
        ("avante", "Avante"),
        ("azera", "Azera"),
        ("bayon", "Bayon"),
        ("casper", "Casper"),
        ("click", "Click"),
        ("coupe", "Coupe"),
        ("creta", "Creta"),
        ("dynasty", "Dynasty"),
        ("elantra", "Elantra"),
        ("encino", "Encino"),
        ("equus", "Equus"),
        ("galloper", "Galloper"),
        ("genesis", "Genesis"),
        ("genesis-coupe", "Genesis Coupe"),
        ("getz", "Getz"),
        ("grand-santa-fe", "Grand Santa Fe"),
        ("grandeur", "Grandeur"),
        ("h-1", "H-1"),
        ("i10", "i10"),
        ("i20", "i20"),
        ("i30", "i30"),
        ("i40", "i40"),
        ("inster", "Inster"),
        ("ioniq", "Ioniq"),
        ("ioniq-5", "Ioniq 5"),
        ("ioniq-6", "Ioniq 6"),
        ("ix20", "ix20"),
        ("ix35", "ix35"),
        ("ix55", "ix55"),
        ("kona", "Kona"),
        ("lafesta", "Lafesta"),
        ("lantra", "Lantra"),
        ("matrix", "Matrix"),
        ("maxcruz", "Maxcruz"),
        ("palisade", "Palisade"),
        ("pony", "Pony"),
        ("porter", "Porter"),
        ("reina", "Reina"),
        ("santa-cruz", "Santa Cruz"),
        ("santa-fe", "Santa Fe"),
        ("solaris", "Solaris"),
        ("sonata", "Sonata"),
        ("starex", "Starex"),
        ("staria", "Staria"),
        ("terracan", "Terracan"),
        ("tiburon", "Tiburon"),
        ("trajet", "Trajet"),
        ("tucson", "Tucson"),
        ("veloster", "Veloster"),
        ("venue", "Venue"),
        ("veracruz", "Veracruz"),
        ("verna", "Verna"),
        ("xg", "XG"),
    ],
    "im": [
        ("l6", "L6"),
        ("l7", "L7"),
        ("ls6", "LS6"),
        ("ls7", "LS7"),
    ],
    "infiniti": [
        ("ex", "EX"),
        ("fx", "FX"),
        ("g", "G"),
        ("i30", "I30"),
        ("i35", "I35"),
        ("jx", "JX"),
        ("m", "M"),
        ("q30", "Q30"),
        ("q50", "Q50"),
        ("q60", "Q60"),
        ("q70", "Q70"),
        ("qx30", "QX30"),
        ("qx50", "QX50"),
        ("qx55", "QX55"),
        ("qx60", "QX60"),
        ("qx70", "QX70"),
        ("qx80", "QX80"),
    ],
    "innocenti": [
        ("elba", "Elba"),
        ("koral", "Koral"),
        ("mille", "Mille"),
        ("mini", "Mini"),
        ("small", "Small"),
    ],
    "isuzu": [
        ("amigo", "Amigo"),
        ("ascender", "Ascender"),
        ("axiom", "Axiom"),
        ("d-max", "D-Max"),
        ("gemini", "Gemini"),
        ("mu", "MU"),
        ("mu-x", "MU-X"),
        ("rodeo", "Rodeo"),
        ("trooper", "Trooper"),
        ("vehicross", "VehiCROSS"),
    ],
    "iveco": [
        ("daily", "Daily"),
        ("eurocargo", "EuroCargo"),
        ("massif", "Massif"),
    ],
    "jac": [
        ("iev7s", "iEV7S"),
        ("ieva50", "iEVA50"),
        ("j2", "J2"),
        ("j3", "J3"),
        ("j5", "J5"),
        ("j6", "J6"),
        ("j7", "J7"),
        ("js2", "JS2"),
        ("js3", "JS3"),
        ("js4", "JS4"),
        ("js6", "JS6"),
        ("js8", "JS8"),
        ("refine", "Refine"),
        ("s2", "S2"),
        ("s3", "S3"),
        ("s4", "S4"),
        ("s5", "S5"),
        ("s7", "S7"),
        ("t6", "T6"),
        ("t8", "T8"),
        ("t9", "T9"),
    ],
    "jaecoo": [
        ("j7", "J7"),
        ("j8", "J8"),
    ],
    "jaguar": [
        ("e-pace", "E-Pace"),
        ("f-pace", "F-Pace"),
        ("f-type", "F-Type"),
        ("i-pace", "I-Pace"),
        ("s-type", "S-Type"),
        ("x-type", "X-Type"),
        ("xe", "XE"),
        ("xf", "XF"),
        ("xj", "XJ"),
        ("xk", "XK"),
    ],
    "jeep": [
        ("avenger", "Avenger"),
        ("cherokee", "Cherokee"),
        ("comanche", "Comanche"),
        ("commander", "Commander"),
        ("compass", "Compass"),
        ("gladiator", "Gladiator"),
        ("grand-cherokee", "Grand Cherokee"),
        ("grand-wagoneer", "Grand Wagoneer"),
        ("liberty", "Liberty"),
        ("patriot", "Patriot"),
        ("renegade", "Renegade"),
        ("wagoneer", "Wagoneer"),
        ("wrangler", "Wrangler"),
    ],
    "jetour": [
        ("dashing", "Dashing"),
        ("shanhai-l6", "Shanhai L6"),
        ("shanhai-l9", "Shanhai L9"),
        ("t1", "T1"),
        ("t2", "T2"),
        ("traveler", "Traveler"),
        ("x50", "X50"),
        ("x70", "X70"),
        ("x70-coupe", "X70 Coupe"),
        ("x70-plus", "X70 Plus"),
        ("x70-pro", "X70 Pro"),
        ("x90", "X90"),
        ("x90-plus", "X90 Plus"),
        ("x95", "X95"),
    ],
    "jetta": [
        ("va3", "VA3"),
        ("va7", "VA7"),
        ("vs5", "VS5"),
        ("vs7", "VS7"),
    ],
    "kaiyi": [
        ("e5", "E5"),
        ("x3", "X3"),
        ("x3-pro", "X3 Pro"),
        ("x7-kunlun", "X7 Kunlun"),
    ],
    "karma": [
        ("gs-6", "GS-6"),
        ("revero", "Revero"),
    ],
    "kia": [
        ("bongo", "Bongo"),
        ("cadenza", "Cadenza"),
        ("carens", "Carens"),
        ("carnival", "Carnival"),
        ("ceed", "Ceed"),
        ("cerato", "Cerato"),
        ("clarus", "Clarus"),
        ("ev3", "EV3"),
        ("ev4", "EV4"),
        ("ev5", "EV5"),
        ("ev6", "EV6"),
        ("ev9", "EV9"),
        ("forte", "Forte"),
        ("k3", "K3"),
        ("k4", "K4"),
        ("k5", "K5"),
        ("k7", "K7"),
        ("k8", "K8"),
        ("k9", "K9"),
        ("magentis", "Magentis"),
        ("mohave", "Mohave"),
        ("morning", "Morning"),
        ("niro", "Niro"),
        ("opirus", "Opirus"),
        ("optima", "Optima"),
        ("picanto", "Picanto"),
        ("proceed", "ProCeed"),
        ("quoris", "Quoris"),
        ("ray", "Ray"),
        ("retona", "Retona"),
        ("rio", "Rio"),
        ("seltos", "Seltos"),
        ("sephia", "Sephia"),
        ("shuma", "Shuma"),
        ("sorento", "Sorento"),
        ("soul", "Soul"),
        ("spectra", "Spectra"),
        ("sportage", "Sportage"),
        ("stinger", "Stinger"),
        ("stonic", "Stonic"),
        ("tasman", "Tasman"),
        ("telluride", "Telluride"),
        ("venga", "Venga"),
        ("x-trek", "X-Trek"),
    ],
    "koenigsegg": [
        ("agera", "Agera"),
        ("cc8s", "CC8S"),
        ("gemera", "Gemera"),
        ("jesko", "Jesko"),
        ("one-1", "One:1"),
        ("regera", "Regera"),
    ],
    "lada": [
        ("110", "110"),
        ("111", "111"),
        ("112", "112"),
        ("2101", "2101"),
        ("2104", "2104"),
        ("2105", "2105"),
        ("2106", "2106"),
        ("2107", "2107"),
        ("2108", "2108"),
        ("2109", "2109"),
        ("2110", "2110"),
        ("2111", "2111"),
        ("2112", "2112"),
        ("2113", "2113"),
        ("2114", "2114"),
        ("2115", "2115"),
        ("granta", "Granta"),
        ("kalina", "Kalina"),
        ("largus", "Largus"),
        ("niva", "Niva"),
        ("niva-legend", "Niva Legend"),
        ("priora", "Priora"),
        ("vesta", "Vesta"),
        ("xray", "XRAY"),
    ],
    "lamborghini": [
        ("aventador", "Aventador"),
        ("countach", "Countach"),
        ("diablo", "Diablo"),
        ("gallardo", "Gallardo"),
        ("huracan", "Huracan"),
        ("murcielago", "Murcielago"),
        ("revuelto", "Revuelto"),
        ("urus", "Urus"),
    ],
    "lancia": [
        ("beta", "Beta"),
        ("dedra", "Dedra"),
        ("delta", "Delta"),
        ("flavia", "Flavia"),
        ("kappa", "Kappa"),
        ("lybra", "Lybra"),
        ("musa", "Musa"),
        ("phedra", "Phedra"),
        ("thema", "Thema"),
        ("thesis", "Thesis"),
        ("ypsilon", "Ypsilon"),
        ("zeta", "Zeta"),
    ],
    "land-rover": [
        ("defender", "Defender"),
        ("discovery", "Discovery"),
        ("discovery-sport", "Discovery Sport"),
        ("freelander", "Freelander"),
        ("range-rover", "Range Rover"),
        ("range-rover-evoque", "Range Rover Evoque"),
        ("range-rover-sport", "Range Rover Sport"),
        ("range-rover-velar", "Range Rover Velar"),
    ],
    "leapmotor": [
        ("c01", "C01"),
        ("c10", "C10"),
        ("c11", "C11"),
        ("c16", "C16"),
        ("t03", "T03"),
    ],
    "lexus": [
        ("ct", "CT"),
        ("es", "ES"),
        ("gs", "GS"),
        ("gx", "GX"),
        ("hs", "HS"),
        ("is", "IS"),
        ("lc", "LC"),
        ("lfa", "LFA"),
        ("lm", "LM"),
        ("ls", "LS"),
        ("lx", "LX"),
        ("nx", "NX"),
        ("rc", "RC"),
        ("rx", "RX"),
        ("rz", "RZ"),
        ("sc", "SC"),
        ("tx", "TX"),
        ("ux", "UX"),
    ],
    "li-auto": [
        ("i8", "i8"),
        ("l6", "L6"),
        ("l7", "L7"),
        ("l8", "L8"),
        ("l9", "L9"),
        ("mega", "Mega"),
        ("one", "One"),
    ],
    "lifan": [
        ("breez", "Breez"),
        ("cebrium", "Cebrium"),
        ("celliya", "Celliya"),
        ("murman", "Murman"),
        ("myway", "MyWay"),
        ("smily", "Smily"),
        ("solano", "Solano"),
        ("x50", "X50"),
        ("x60", "X60"),
        ("x70", "X70"),
    ],
    "lincoln": [
        ("aviator", "Aviator"),
        ("blackwood", "Blackwood"),
        ("continental", "Continental"),
        ("corsair", "Corsair"),
        ("ls", "LS"),
        ("mark", "Mark"),
        ("mark-lt", "Mark LT"),
        ("mkc", "MKC"),
        ("mks", "MKS"),
        ("mkt", "MKT"),
        ("mkx", "MKX"),
        ("mkz", "MKZ"),
        ("nautilus", "Nautilus"),
        ("navigator", "Navigator"),
        ("town-car", "Town Car"),
        ("zephyr", "Zephyr"),
    ],
    "lotus": [
        ("elan", "Elan"),
        ("elise", "Elise"),
        ("emeya", "Emeya"),
        ("emira", "Emira"),
        ("esprit", "Esprit"),
        ("europa", "Europa"),
        ("evija", "Evija"),
        ("evora", "Evora"),
        ("exige", "Exige"),
    ],
    "lucid": [
        ("air", "Air"),
        ("gravity", "Gravity"),
    ],
    "luxgen": [
        ("5", "5"),
        ("7", "7"),
        ("m7", "M7"),
        ("s3", "S3"),
        ("s5", "S5"),
        ("u6", "U6"),
        ("u7", "U7"),
        ("v7", "V7"),
    ],
    "lynk-co": [
        ("01", "01"),
        ("02", "02"),
        ("03", "03"),
        ("05", "05"),
        ("06", "06"),
        ("07", "07"),
        ("08", "08"),
        ("09", "09"),
        ("10", "10"),
        ("z10", "Z10"),
        ("z20", "Z20"),
    ],
    "maserati": [
        ("3200-gt", "3200 GT"),
        ("biturbo", "Biturbo"),
        ("coupe", "Coupe"),
        ("ghibli", "Ghibli"),
        ("grancabrio", "GranCabrio"),
        ("granturismo", "GranTurismo"),
        ("grecale", "Grecale"),
        ("levante", "Levante"),
        ("mc20", "MC20"),
        ("quattroporte", "Quattroporte"),
        ("spyder", "Spyder"),
    ],
    "maxus": [
        ("d60", "D60"),
        ("d90", "D90"),
        ("eterron-9", "eTerron 9"),
        ("euniq-5", "Euniq 5"),
        ("euniq-6", "Euniq 6"),
        ("g10", "G10"),
        ("g20", "G20"),
        ("g50", "G50"),
        ("mifa-9", "Mifa 9"),
        ("t60", "T60"),
        ("t70", "T70"),
        ("t90", "T90"),
        ("v80", "V80"),
        ("v90", "V90"),
    ],
    "maybach": [
        ("57", "57"),
        ("62", "62"),
        ("s-class", "S-Class"),
    ],
    "mazda": [
        ("121", "121"),
        ("2", "2"),
        ("3", "3"),
        ("323", "323"),
        ("5", "5"),
        ("6", "6"),
        ("626", "626"),
        ("929", "929"),
        ("b-series", "B-Series"),
        ("bt-50", "BT-50"),
        ("cx-3", "CX-3"),
        ("cx-30", "CX-30"),
        ("cx-5", "CX-5"),
        ("cx-50", "CX-50"),
        ("cx-60", "CX-60"),
        ("cx-7", "CX-7"),
        ("cx-70", "CX-70"),
        ("cx-8", "CX-8"),
        ("cx-9", "CX-9"),
        ("cx-90", "CX-90"),
        ("demio", "Demio"),
        ("eunos", "Eunos"),
        ("familia", "Familia"),
        ("luce", "Luce"),
        ("mpv", "MPV"),
        ("mx-3", "MX-3"),
        ("mx-30", "MX-30"),
        ("mx-5", "MX-5"),
        ("mx-6", "MX-6"),
        ("premacy", "Premacy"),
        ("proceed", "Proceed"),
        ("revue", "Revue"),
        ("rx-7", "RX-7"),
        ("rx-8", "RX-8"),
        ("scrum", "Scrum"),
        ("sentia", "Sentia"),
        ("tribute", "Tribute"),
        ("xedos", "Xedos"),
    ],
    "mclaren": [
        ("540c", "540C"),
        ("570s", "570S"),
        ("600lt", "600LT"),
        ("650s", "650S"),
        ("675lt", "675LT"),
        ("720s", "720S"),
        ("750s", "750S"),
        ("765lt", "765LT"),
        ("artura", "Artura"),
        ("f1", "F1"),
        ("gt", "GT"),
        ("mp4-12c", "MP4-12C"),
        ("p1", "P1"),
        ("senna", "Senna"),
    ],
    "mercedes-benz": [
        ("190", "190"),
        ("a-class", "A-Class"),
        ("amg-gt", "AMG GT"),
        ("b-class", "B-Class"),
        ("c-class", "C-Class"),
        ("cl", "CL"),
        ("cla", "CLA"),
        ("clc", "CLC"),
        ("clk", "CLK"),
        ("cls", "CLS"),
        ("e-class", "E-Class"),
        ("eqa", "EQA"),
        ("eqb", "EQB"),
        ("eqc", "EQC"),
        ("eqe", "EQE"),
        ("eqe-suv", "EQE SUV"),
        ("eqs", "EQS"),
        ("eqs-suv", "EQS SUV"),
        ("eqv", "EQV"),
        ("g-class", "G-Class"),
        ("gl", "GL"),
        ("gla", "GLA"),
        ("glb", "GLB"),
        ("glc", "GLC"),
        ("gle", "GLE"),
        ("gle-coupe", "GLE Coupe"),
        ("glk", "GLK"),
        ("gls", "GLS"),
        ("maybach-gls", "Maybach GLS"),
        ("maybach-s-class", "Maybach S-Class"),
        ("ml", "ML"),
        ("r-class", "R-Class"),
        ("s-class", "S-Class"),
        ("sl", "SL"),
        ("slc", "SLC"),
        ("slk", "SLK"),
        ("slr", "SLR"),
        ("sls", "SLS"),
        ("sprinter", "Sprinter"),
        ("v-class", "V-Class"),
        ("vaneo", "Vaneo"),
        ("viano", "Viano"),
        ("vito", "Vito"),
        ("x-class", "X-Class"),
    ],
    "mercury": [
        ("cougar", "Cougar"),
        ("grand-marquis", "Grand Marquis"),
        ("marauder", "Marauder"),
        ("mariner", "Mariner"),
        ("milan", "Milan"),
        ("montego", "Montego"),
        ("mountaineer", "Mountaineer"),
        ("sable", "Sable"),
        ("villager", "Villager"),
    ],
    "mg": [
        ("3", "3"),
        ("4", "4"),
        ("5", "5"),
        ("6", "6"),
        ("7", "7"),
        ("cyberster", "Cyberster"),
        ("f", "F"),
        ("gs", "GS"),
        ("hs", "HS"),
        ("marvel-r", "Marvel R"),
        ("mg4", "MG4"),
        ("one", "One"),
        ("rx5", "RX5"),
        ("rx8", "RX8"),
        ("tf", "TF"),
        ("zs", "ZS"),
        ("zt", "ZT"),
    ],
    "microcar": [
        ("due", "Due"),
        ("flex", "Flex"),
        ("highland", "Highland"),
        ("m-go", "M.Go"),
        ("m8", "M8"),
        ("mc1", "MC1"),
        ("mc2", "MC2"),
        ("virgo", "Virgo"),
    ],
    "mini": [
        ("clubman", "Clubman"),
        ("cooper", "Cooper"),
        ("countryman", "Countryman"),
        ("coupe", "Coupe"),
        ("hatch", "Hatch"),
        ("paceman", "Paceman"),
        ("roadster", "Roadster"),
    ],
    "mitsubishi": [
        ("3000gt", "3000GT"),
        ("asx", "ASX"),
        ("carisma", "Carisma"),
        ("colt", "Colt"),
        ("diamante", "Diamante"),
        ("eclipse", "Eclipse"),
        ("eclipse-cross", "Eclipse Cross"),
        ("endeavor", "Endeavor"),
        ("galant", "Galant"),
        ("grandis", "Grandis"),
        ("i-miev", "i-MiEV"),
        ("l200", "L200"),
        ("lancer", "Lancer"),
        ("mirage", "Mirage"),
        ("montero", "Montero"),
        ("outlander", "Outlander"),
        ("pajero", "Pajero"),
        ("pajero-sport", "Pajero Sport"),
        ("rvr", "RVR"),
        ("space-gear", "Space Gear"),
        ("space-star", "Space Star"),
        ("space-wagon", "Space Wagon"),
        ("xpander", "Xpander"),
    ],
    "mitsuoka": [
        ("buddy", "Buddy"),
        ("galue", "Galue"),
        ("himiko", "Himiko"),
        ("le-seyde", "Le-Seyde"),
        ("like", "Like"),
        ("nouera", "Nouera"),
        ("orochi", "Orochi"),
        ("rock-star", "Rock Star"),
        ("ryoga", "Ryoga"),
        ("ryugi", "Ryugi"),
        ("viewt", "Viewt"),
    ],
    "morgan": [
        ("3-wheeler", "3 Wheeler"),
        ("4-4", "4/4"),
        ("aero-8", "Aero 8"),
        ("aero-supersports", "Aero SuperSports"),
        ("plus-4", "Plus 4"),
        ("plus-6", "Plus 6"),
        ("plus-8", "Plus 8"),
        ("roadster", "Roadster"),
    ],
    "moskvich": [
        ("3", "3"),
        ("3e", "3e"),
        ("6", "6"),
    ],
    "neta": [
        ("aya", "AYA"),
        ("gt", "GT"),
        ("l", "L"),
        ("n01", "N01"),
        ("s", "S"),
        ("u", "U"),
        ("v", "V"),
        ("x", "X"),
    ],
    "nio": [
        ("ec6", "EC6"),
        ("ec7", "EC7"),
        ("el6", "EL6"),
        ("el7", "EL7"),
        ("el8", "EL8"),
        ("ep9", "EP9"),
        ("es6", "ES6"),
        ("es7", "ES7"),
        ("es8", "ES8"),
        ("et5", "ET5"),
        ("et5t", "ET5T"),
        ("et7", "ET7"),
        ("et9", "ET9"),
    ],
    "nissan": [
        ("350z", "350Z"),
        ("370z", "370Z"),
        ("almera", "Almera"),
        ("almera-classic", "Almera Classic"),
        ("altima", "Altima"),
        ("ariya", "Ariya"),
        ("armada", "Armada"),
        ("bluebird", "Bluebird"),
        ("cube", "Cube"),
        ("elgrand", "Elgrand"),
        ("fairlady-z", "Fairlady Z"),
        ("frontier", "Frontier"),
        ("fuga", "Fuga"),
        ("gt-r", "GT-R"),
        ("juke", "Juke"),
        ("kicks", "Kicks"),
        ("leaf", "Leaf"),
        ("livina", "Livina"),
        ("march", "March"),
        ("maxima", "Maxima"),
        ("micra", "Micra"),
        ("murano", "Murano"),
        ("navara", "Navara"),
        ("note", "Note"),
        ("nv200", "NV200"),
        ("nv300", "NV300"),
        ("pathfinder", "Pathfinder"),
        ("patrol", "Patrol"),
        ("pino", "Pino"),
        ("pixo", "Pixo"),
        ("primera", "Primera"),
        ("pulsar", "Pulsar"),
        ("qashqai", "Qashqai"),
        ("quest", "Quest"),
        ("rogue", "Rogue"),
        ("roox", "Roox"),
        ("sentra", "Sentra"),
        ("serena", "Serena"),
        ("skyline", "Skyline"),
        ("stagea", "Stagea"),
        ("sunny", "Sunny"),
        ("teana", "Teana"),
        ("terrano", "Terrano"),
        ("tiida", "Tiida"),
        ("titan", "Titan"),
        ("townstar", "Townstar"),
        ("versa", "Versa"),
        ("wingroad", "Wingroad"),
        ("x-trail", "X-Trail"),
        ("xterra", "Xterra"),
    ],
    "oldsmobile": [
        ("achieva", "Achieva"),
        ("alero", "Alero"),
        ("aurora", "Aurora"),
        ("bravada", "Bravada"),
        ("ciera", "Ciera"),
        ("cutlass", "Cutlass"),
        ("intrigue", "Intrigue"),
        ("silhouette", "Silhouette"),
        ("toronado", "Toronado"),
    ],
    "omoda": [
        ("c5", "C5"),
        ("c7", "C7"),
        ("c9", "C9"),
        ("e5", "E5"),
        ("s5", "S5"),
    ],
    "opel": [
        ("adam", "Adam"),
        ("agila", "Agila"),
        ("antara", "Antara"),
        ("ascona", "Ascona"),
        ("astra", "Astra"),
        ("calibra", "Calibra"),
        ("cascada", "Cascada"),
        ("combo", "Combo"),
        ("corsa", "Corsa"),
        ("crossland", "Crossland"),
        ("frontera", "Frontera"),
        ("grandland", "Grandland"),
        ("gt", "GT"),
        ("insignia", "Insignia"),
        ("kadett", "Kadett"),
        ("meriva", "Meriva"),
        ("mokka", "Mokka"),
        ("monterey", "Monterey"),
        ("omega", "Omega"),
        ("rekord", "Rekord"),
        ("signum", "Signum"),
        ("sintra", "Sintra"),
        ("speedster", "Speedster"),
        ("tigra", "Tigra"),
        ("vectra", "Vectra"),
        ("vivaro", "Vivaro"),
        ("zafira", "Zafira"),
    ],
    "ora": [
        ("03", "03"),
        ("07", "07"),
        ("ballet-cat", "Ballet Cat"),
        ("good-cat", "Good Cat"),
        ("lightning-cat", "Lightning Cat"),
        ("punk-cat", "Punk Cat"),
    ],
    "pagani": [
        ("huayra", "Huayra"),
        ("zonda", "Zonda"),
    ],
    "peugeot": [
        ("1007", "1007"),
        ("106", "106"),
        ("107", "107"),
        ("108", "108"),
        ("2008", "2008"),
        ("205", "205"),
        ("206", "206"),
        ("207", "207"),
        ("208", "208"),
        ("3008", "3008"),
        ("301", "301"),
        ("306", "306"),
        ("307", "307"),
        ("308", "308"),
        ("4007", "4007"),
        ("4008", "4008"),
        ("405", "405"),
        ("406", "406"),
        ("407", "407"),
        ("408", "408"),
        ("5008", "5008"),
        ("508", "508"),
        ("605", "605"),
        ("607", "607"),
        ("806", "806"),
        ("807", "807"),
        ("partner", "Partner"),
        ("rcz", "RCZ"),
        ("rifter", "Rifter"),
        ("traveller", "Traveller"),
    ],
    "plymouth": [
        ("acclaim", "Acclaim"),
        ("breeze", "Breeze"),
        ("laser", "Laser"),
        ("neon", "Neon"),
        ("prowler", "Prowler"),
        ("voyager", "Voyager"),
    ],
    "polestar": [
        ("1", "1"),
        ("2", "2"),
        ("3", "3"),
        ("4", "4"),
    ],
    "pontiac": [
        ("aztek", "Aztek"),
        ("bonneville", "Bonneville"),
        ("fiero", "Fiero"),
        ("firebird", "Firebird"),
        ("g3", "G3"),
        ("g5", "G5"),
        ("g6", "G6"),
        ("g8", "G8"),
        ("grand-am", "Grand AM"),
        ("grand-prix", "Grand Prix"),
        ("gto", "GTO"),
        ("lemans", "LeMans"),
        ("montana", "Montana"),
        ("solstice", "Solstice"),
        ("sunbird", "Sunbird"),
        ("sunfire", "Sunfire"),
        ("tempest", "Tempest"),
        ("torrent", "Torrent"),
        ("trans-sport", "Trans Sport"),
        ("vibe", "Vibe"),
    ],
    "porsche": [
        ("356", "356"),
        ("911", "911"),
        ("918", "918"),
        ("924", "924"),
        ("928", "928"),
        ("944", "944"),
        ("968", "968"),
        ("boxster", "Boxster"),
        ("cayenne", "Cayenne"),
        ("cayman", "Cayman"),
        ("macan", "Macan"),
        ("panamera", "Panamera"),
        ("taycan", "Taycan"),
    ],
    "proton": [
        ("exora", "Exora"),
        ("gen-2", "Gen-2"),
        ("persona", "Persona"),
        ("preve", "Preve"),
        ("saga", "Saga"),
        ("satria", "Satria"),
        ("savvy", "Savvy"),
        ("waja", "Waja"),
        ("wira", "Wira"),
        ("x50", "X50"),
        ("x70", "X70"),
    ],
    "ram": [
        ("1500", "1500"),
        ("2500", "2500"),
        ("3500", "3500"),
        ("promaster", "ProMaster"),
    ],
    "ravon": [
        ("gentra", "Gentra"),
        ("nexia-r3", "Nexia R3"),
        ("r2", "R2"),
        ("r4", "R4"),
    ],
    "renault": [
        ("arkana", "Arkana"),
        ("austral", "Austral"),
        ("captur", "Captur"),
        ("clio", "Clio"),
        ("dokker", "Dokker"),
        ("duster", "Duster"),
        ("espace", "Espace"),
        ("fluence", "Fluence"),
        ("grand-scenic", "Grand Scenic"),
        ("kadjar", "Kadjar"),
        ("kangoo", "Kangoo"),
        ("kaptur", "Kaptur"),
        ("koleos", "Koleos"),
        ("laguna", "Laguna"),
        ("latitude", "Latitude"),
        ("logan", "Logan"),
        ("megane", "Megane"),
        ("modus", "Modus"),
        ("rafale", "Rafale"),
        ("safrane", "Safrane"),
        ("sandero", "Sandero"),
        ("scenic", "Scenic"),
        ("symbol", "Symbol"),
        ("talisman", "Talisman"),
        ("trafic", "Trafic"),
        ("twingo", "Twingo"),
        ("vel-satis", "Vel Satis"),
        ("wind", "Wind"),
        ("zoe", "Zoe"),
    ],
    "renault-samsung": [
        ("qm3", "QM3"),
        ("qm5", "QM5"),
        ("qm6", "QM6"),
        ("sm3", "SM3"),
        ("sm5", "SM5"),
        ("sm6", "SM6"),
        ("sm7", "SM7"),
        ("xm3", "XM3"),
    ],
    "rimac": [
        ("concept-one", "Concept One"),
        ("concept-two", "Concept Two"),
        ("nevera", "Nevera"),
    ],
    "rivian": [
        ("r1s", "R1S"),
        ("r1t", "R1T"),
        ("r2", "R2"),
        ("r3", "R3"),
    ],
    "roewe": [
        ("550", "550"),
        ("750", "750"),
        ("950", "950"),
        ("ei5", "Ei5"),
        ("i5", "i5"),
        ("i6", "i6"),
        ("rx5", "RX5"),
        ("rx8", "RX8"),
        ("rx9", "RX9"),
        ("w5", "W5"),
    ],
    "rolls-royce": [
        ("corniche", "Corniche"),
        ("cullinan", "Cullinan"),
        ("dawn", "Dawn"),
        ("ghost", "Ghost"),
        ("phantom", "Phantom"),
        ("silver-seraph", "Silver Seraph"),
        ("silver-shadow", "Silver Shadow"),
        ("spectre", "Spectre"),
        ("wraith", "Wraith"),
    ],
    "rover": [
        ("200", "200"),
        ("25", "25"),
        ("400", "400"),
        ("45", "45"),
        ("600", "600"),
        ("75", "75"),
        ("800", "800"),
        ("streetwise", "Streetwise"),
    ],
    "saab": [
        ("9-3", "9-3"),
        ("9-5", "9-5"),
        ("900", "900"),
        ("9000", "9000"),
        ("93", "93"),
        ("95", "95"),
        ("96", "96"),
    ],
    "saturn": [
        ("aura", "Aura"),
        ("ion", "Ion"),
        ("outlook", "Outlook"),
        ("sky", "Sky"),
        ("vue", "Vue"),
    ],
    "scion": [
        ("fr-s", "FR-S"),
        ("tc", "tC"),
        ("xa", "xA"),
        ("xb", "xB"),
        ("xd", "xD"),
    ],
    "seat": [
        ("alhambra", "Alhambra"),
        ("altea", "Altea"),
        ("arona", "Arona"),
        ("arosa", "Arosa"),
        ("ateca", "Ateca"),
        ("cordoba", "Cordoba"),
        ("exeo", "Exeo"),
        ("ibiza", "Ibiza"),
        ("leon", "Leon"),
        ("malaga", "Malaga"),
        ("marbella", "Marbella"),
        ("mii", "Mii"),
        ("tarraco", "Tarraco"),
        ("toledo", "Toledo"),
    ],
    "seres": [
        ("3", "3"),
        ("5", "5"),
        ("7", "7"),
        ("9", "9"),
    ],
    "skoda": [
        ("citigo", "Citigo"),
        ("enyaq", "Enyaq"),
        ("fabia", "Fabia"),
        ("favorit", "Favorit"),
        ("felicia", "Felicia"),
        ("kamiq", "Kamiq"),
        ("karoq", "Karoq"),
        ("kodiaq", "Kodiaq"),
        ("octavia", "Octavia"),
        ("praktik", "Praktik"),
        ("rapid", "Rapid"),
        ("roomster", "Roomster"),
        ("scala", "Scala"),
        ("superb", "Superb"),
        ("yeti", "Yeti"),
    ],
    "smart": [
        ("1", "#1"),
        ("3", "#3"),
        ("forfour", "Forfour"),
        ("fortwo", "Fortwo"),
        ("roadster", "Roadster"),
    ],
    "soueast": [
        ("a5", "A5"),
        ("dx3", "DX3"),
        ("dx5", "DX5"),
        ("dx7", "DX7"),
        ("dx8", "DX8"),
        ("dx8s", "DX8S"),
        ("lioncel", "Lioncel"),
        ("v3", "V3"),
        ("v5", "V5"),
        ("v6", "V6"),
    ],
    "ssangyong": [
        ("actyon", "Actyon"),
        ("chairman", "Chairman"),
        ("istana", "Istana"),
        ("korando", "Korando"),
        ("kyron", "Kyron"),
        ("musso", "Musso"),
        ("rexton", "Rexton"),
        ("rodius", "Rodius"),
        ("stavic", "Stavic"),
        ("tivoli", "Tivoli"),
        ("torres", "Torres"),
        ("xlv", "XLV"),
    ],
    "subaru": [
        ("ascent", "Ascent"),
        ("brz", "BRZ"),
        ("crosstrek", "Crosstrek"),
        ("domingo", "Domingo"),
        ("exiga", "Exiga"),
        ("forester", "Forester"),
        ("impreza", "Impreza"),
        ("justy", "Justy"),
        ("legacy", "Legacy"),
        ("levorg", "Levorg"),
        ("outback", "Outback"),
        ("rex", "Rex"),
        ("sambar", "Sambar"),
        ("solterra", "Solterra"),
        ("svx", "SVX"),
        ("tribeca", "Tribeca"),
        ("wrx", "WRX"),
        ("xv", "XV"),
    ],
    "suzuki": [
        ("across", "Across"),
        ("alto", "Alto"),
        ("baleno", "Baleno"),
        ("celerio", "Celerio"),
        ("ciaz", "Ciaz"),
        ("ertiga", "Ertiga"),
        ("escudo", "Escudo"),
        ("every", "Every"),
        ("grand-escudo", "Grand Escudo"),
        ("grand-vitara", "Grand Vitara"),
        ("ignis", "Ignis"),
        ("jimny", "Jimny"),
        ("kei", "Kei"),
        ("kizashi", "Kizashi"),
        ("landy", "Landy"),
        ("liana", "Liana"),
        ("mr-wagon", "MR Wagon"),
        ("palette", "Palette"),
        ("samurai", "Samurai"),
        ("solio", "Solio"),
        ("spacia", "Spacia"),
        ("splash", "Splash"),
        ("swace", "Swace"),
        ("swift", "Swift"),
        ("sx4", "SX4"),
        ("twin", "Twin"),
        ("vitara", "Vitara"),
        ("wagon-r", "Wagon R"),
        ("x-90", "X-90"),
        ("xl7", "XL7"),
    ],
    "tank": [
        ("300", "300"),
        ("330", "330"),
        ("400", "400"),
        ("500", "500"),
        ("700", "700"),
    ],
    "tata": [
        ("aria", "Aria"),
        ("harrier", "Harrier"),
        ("indica", "Indica"),
        ("indigo", "Indigo"),
        ("nano", "Nano"),
        ("nexon", "Nexon"),
        ("safari", "Safari"),
        ("sierra", "Sierra"),
        ("sumo", "Sumo"),
        ("telcoline", "Telcoline"),
        ("tiago", "Tiago"),
        ("tigor", "Tigor"),
    ],
    "tesla": [
        ("cybertruck", "Cybertruck"),
        ("model-3", "Model 3"),
        ("model-s", "Model S"),
        ("model-x", "Model X"),
        ("model-y", "Model Y"),
        ("roadster", "Roadster"),
    ],
    "toyota": [
        ("4runner", "4Runner"),
        ("alphard", "Alphard"),
        ("auris", "Auris"),
        ("avalon", "Avalon"),
        ("avensis", "Avensis"),
        ("aygo", "Aygo"),
        ("bz3", "bZ3"),
        ("bz4x", "bZ4X"),
        ("c-hr", "C-HR"),
        ("camry", "Camry"),
        ("celica", "Celica"),
        ("corolla", "Corolla"),
        ("corolla-cross", "Corolla Cross"),
        ("crown", "Crown"),
        ("echo", "Echo"),
        ("estima", "Estima"),
        ("fj-cruiser", "FJ Cruiser"),
        ("fortuner", "Fortuner"),
        ("gr86", "GR86"),
        ("granvia", "Granvia"),
        ("gt86", "GT86"),
        ("harrier", "Harrier"),
        ("hiace", "Hiace"),
        ("highlander", "Highlander"),
        ("hilux", "Hilux"),
        ("isis", "Isis"),
        ("ist", "Ist"),
        ("land-cruiser", "Land Cruiser"),
        ("land-cruiser-prado", "Land Cruiser Prado"),
        ("lite-ace", "Lite Ace"),
        ("mark-x", "Mark X"),
        ("matrix", "Matrix"),
        ("mirai", "Mirai"),
        ("mr2", "MR2"),
        ("noah", "Noah"),
        ("picnic", "Picnic"),
        ("prado", "Prado"),
        ("premio", "Premio"),
        ("previa", "Previa"),
        ("prius", "Prius"),
        ("proace", "Proace"),
        ("raize", "Raize"),
        ("rav4", "RAV4"),
        ("rush", "Rush"),
        ("sequoia", "Sequoia"),
        ("sienna", "Sienna"),
        ("sienta", "Sienta"),
        ("soarer", "Soarer"),
        ("solara", "Solara"),
        ("starlet", "Starlet"),
        ("supra", "Supra"),
        ("tacoma", "Tacoma"),
        ("tundra", "Tundra"),
        ("urban-cruiser", "Urban Cruiser"),
        ("vanguard", "Vanguard"),
        ("venza", "Venza"),
        ("verso", "Verso"),
        ("vitz", "Vitz"),
        ("voxy", "Voxy"),
        ("wish", "Wish"),
        ("yaris", "Yaris"),
        ("yaris-cross", "Yaris Cross"),
        ("yaris-verso", "Yaris Verso"),
    ],
    "tvr": [
        ("cerbera", "Cerbera"),
        ("chimaera", "Chimaera"),
        ("griffith", "Griffith"),
        ("sagaris", "Sagaris"),
        ("tamora", "Tamora"),
        ("tuscan", "Tuscan"),
    ],
    "uaz": [
        ("3151", "3151"),
        ("3159", "3159"),
        ("3160", "3160"),
        ("452", "452"),
        ("469", "469"),
        ("hunter", "Hunter"),
        ("patriot", "Patriot"),
        ("pickup", "Pickup"),
        ("profi", "Profi"),
        ("simbir", "Simbir"),
    ],
    "vauxhall": [
        ("adam", "Adam"),
        ("astra", "Astra"),
        ("cascada", "Cascada"),
        ("combo", "Combo"),
        ("corsa", "Corsa"),
        ("crossland", "Crossland"),
        ("frontera", "Frontera"),
        ("grandland", "Grandland"),
        ("insignia", "Insignia"),
        ("meriva", "Meriva"),
        ("mokka", "Mokka"),
        ("omega", "Omega"),
        ("signum", "Signum"),
        ("vectra", "Vectra"),
        ("vivaro", "Vivaro"),
        ("zafira", "Zafira"),
    ],
    "venucia": [
        ("d50", "D50"),
        ("d60", "D60"),
        ("e30", "e30"),
        ("m50v", "M50V"),
        ("r30", "R30"),
        ("r50", "R50"),
        ("r50x", "R50X"),
        ("star", "Star"),
        ("t60", "T60"),
        ("t70", "T70"),
        ("t90", "T90"),
        ("v-online", "V-Online"),
    ],
    "volkswagen": [
        ("amarok", "Amarok"),
        ("arteon", "Arteon"),
        ("beetle", "Beetle"),
        ("bora", "Bora"),
        ("caddy", "Caddy"),
        ("california", "California"),
        ("caravelle", "Caravelle"),
        ("corrado", "Corrado"),
        ("crafter", "Crafter"),
        ("derby", "Derby"),
        ("eos", "Eos"),
        ("fox", "Fox"),
        ("golf", "Golf"),
        ("id-2", "ID.2"),
        ("id-3", "ID.3"),
        ("id-4", "ID.4"),
        ("id-5", "ID.5"),
        ("id-6", "ID.6"),
        ("id-7", "ID.7"),
        ("id-buzz", "ID.Buzz"),
        ("jetta", "Jetta"),
        ("lupo", "Lupo"),
        ("multivan", "Multivan"),
        ("parati", "Parati"),
        ("passat", "Passat"),
        ("passat-cc", "Passat CC"),
        ("phaeton", "Phaeton"),
        ("pointer", "Pointer"),
        ("polo", "Polo"),
        ("santana", "Santana"),
        ("saveiro", "Saveiro"),
        ("scirocco", "Scirocco"),
        ("sharan", "Sharan"),
        ("t-cross", "T-Cross"),
        ("t-roc", "T-Roc"),
        ("taigo", "Taigo"),
        ("taos", "Taos"),
        ("tayron", "Tayron"),
        ("teramont", "Teramont"),
        ("tiguan", "Tiguan"),
        ("touareg", "Touareg"),
        ("touran", "Touran"),
        ("transporter", "Transporter"),
        ("up", "Up"),
        ("vento", "Vento"),
        ("virtus", "Virtus"),
    ],
    "volvo": [
        ("240", "240"),
        ("340", "340"),
        ("440", "440"),
        ("460", "460"),
        ("740", "740"),
        ("760", "760"),
        ("850", "850"),
        ("940", "940"),
        ("960", "960"),
        ("c30", "C30"),
        ("c40", "C40"),
        ("c70", "C70"),
        ("em90", "EM90"),
        ("ex30", "EX30"),
        ("ex90", "EX90"),
        ("s40", "S40"),
        ("s60", "S60"),
        ("s70", "S70"),
        ("s80", "S80"),
        ("s90", "S90"),
        ("v40", "V40"),
        ("v50", "V50"),
        ("v60", "V60"),
        ("v70", "V70"),
        ("v90", "V90"),
        ("xc40", "XC40"),
        ("xc60", "XC60"),
        ("xc70", "XC70"),
        ("xc90", "XC90"),
    ],
    "voyah": [
        ("dream", "Dream"),
        ("free", "Free"),
        ("passion", "Passion"),
    ],
    "weltmeister": [
        ("e5", "E5"),
        ("ex5", "EX5"),
        ("ex6", "EX6"),
        ("m7", "M7"),
        ("w6", "W6"),
    ],
    "wey": [
        ("03", "03"),
        ("05", "05"),
        ("07", "07"),
        ("80", "80"),
        ("blue-mountain", "Blue Mountain"),
        ("coffee-01", "Coffee 01"),
        ("gaoshan", "Gaoshan"),
        ("latte", "Latte"),
        ("macchiato", "Macchiato"),
    ],
    "wuling": [
        ("air-ev", "Air EV"),
        ("almaz", "Almaz"),
        ("bingo", "Bingo"),
        ("bingo-plus", "Bingo Plus"),
        ("cloud", "Cloud"),
        ("cortez", "Cortez"),
        ("formo", "Formo"),
        ("hongguang", "Hongguang"),
        ("hongguang-mini-ev", "Hongguang Mini EV"),
        ("hongguang-plus", "Hongguang Plus"),
        ("jiachen", "Jiachen"),
        ("journey", "Journey"),
        ("mini-ev", "Mini EV"),
        ("nano-ev", "Nano EV"),
        ("starlight", "Starlight"),
        ("sunshine", "Sunshine"),
        ("victory", "Victory"),
        ("xingguang", "Xingguang"),
    ],
    "xpeng": [
        ("g3", "G3"),
        ("g3i", "G3i"),
        ("g6", "G6"),
        ("g9", "G9"),
        ("mona-m03", "Mona M03"),
        ("p5", "P5"),
        ("p7", "P7"),
        ("p7-2", "P7+"),
        ("p7i", "P7i"),
        ("x9", "X9"),
    ],
    "yangwang": [
        ("u7", "U7"),
        ("u8", "U8"),
        ("u9", "U9"),
    ],
    "zeekr": [
        ("001", "001"),
        ("001-fr", "001 FR"),
        ("007", "007"),
        ("007-gt", "007 GT"),
        ("009", "009"),
        ("009-grand", "009 Grand"),
        ("7gt", "7GT"),
        ("7x", "7X"),
        ("9x", "9X"),
        ("mix", "Mix"),
        ("x", "X"),
    ],
    "zotye": [
        ("2008", "2008"),
        ("5008", "5008"),
        ("domy", "Domy"),
        ("sr7", "SR7"),
        ("sr9", "SR9"),
        ("t300", "T300"),
        ("t500", "T500"),
        ("t600", "T600"),
        ("t700", "T700"),
        ("z100", "Z100"),
        ("z300", "Z300"),
        ("z500", "Z500"),
        ("z700", "Z700"),
    ],
    "zx": [
        ("grand-tiger", "Grand Tiger"),
        ("landmark", "Landmark"),
        ("terralord", "Terralord"),
    ],
}

MOBILE_VEHICLE_CATALOG_COUNTS = {
    "brands": 160,
    "models": 2147,
    "popular_brands": 15,
}
