from __future__ import annotations

from app.models.category_enums import VehicleAliasTarget, VehicleType

# (slug, name, country, vehicle_type)
BRANDS: list[tuple[str, str, str | None, VehicleType]] = [
    # Japanese
    ("toyota", "Toyota", "Japan", VehicleType.car),
    ("honda", "Honda", "Japan", VehicleType.car),
    ("nissan", "Nissan", "Japan", VehicleType.car),
    ("mazda", "Mazda", "Japan", VehicleType.car),
    ("mitsubishi", "Mitsubishi", "Japan", VehicleType.car),
    ("subaru", "Subaru", "Japan", VehicleType.car),
    ("lexus", "Lexus", "Japan", VehicleType.car),
    ("suzuki", "Suzuki", "Japan", VehicleType.car),
    ("isuzu", "Isuzu", "Japan", VehicleType.truck),
    # Korean
    ("hyundai", "Hyundai", "Korea", VehicleType.car),
    ("kia", "Kia", "Korea", VehicleType.car),
    ("genesis", "Genesis", "Korea", VehicleType.car),
    ("ssangyong", "SsangYong", "Korea", VehicleType.car),
    ("daewoo", "Daewoo", "Korea", VehicleType.car),
    # Chinese
    ("byd", "BYD", "China", VehicleType.car),
    ("geely", "Geely", "China", VehicleType.car),
    ("chery", "Chery", "China", VehicleType.car),
    ("haval", "Haval", "China", VehicleType.car),
    ("changan", "Changan", "China", VehicleType.car),
    ("li-auto", "Li Auto", "China", VehicleType.car),
    ("lixiang", "Lixiang", "China", VehicleType.car),
    ("nio", "NIO", "China", VehicleType.car),
    ("zeekr", "Zeekr", "China", VehicleType.car),
    ("jetour", "Jetour", "China", VehicleType.car),
    ("tank", "Tank", "China", VehicleType.car),
    ("omoda", "Omoda", "China", VehicleType.car),
    ("exeed", "Exeed", "China", VehicleType.car),
    ("great-wall", "Great Wall", "China", VehicleType.car),
    ("dongfeng", "Dongfeng", "China", VehicleType.truck),
    # European
    ("mercedes-benz", "Mercedes-Benz", "Germany", VehicleType.car),
    ("bmw", "BMW", "Germany", VehicleType.car),
    ("audi", "Audi", "Germany", VehicleType.car),
    ("volkswagen", "Volkswagen", "Germany", VehicleType.car),
    ("porsche", "Porsche", "Germany", VehicleType.car),
    ("volvo", "Volvo", "Sweden", VehicleType.car),
    ("renault", "Renault", "France", VehicleType.car),
    ("peugeot", "Peugeot", "France", VehicleType.car),
    ("skoda", "Skoda", "Czech", VehicleType.car),
    ("opel", "Opel", "Germany", VehicleType.car),
    ("citroen", "Citroen", "France", VehicleType.car),
    # American
    ("ford", "Ford", "USA", VehicleType.car),
    ("chevrolet", "Chevrolet", "USA", VehicleType.car),
    ("tesla", "Tesla", "USA", VehicleType.car),
    ("jeep", "Jeep", "USA", VehicleType.car),
    ("cadillac", "Cadillac", "USA", VehicleType.car),
    ("dodge", "Dodge", "USA", VehicleType.car),
    # Russian
    ("lada", "Lada", "Russia", VehicleType.car),
    ("uaz", "UAZ", "Russia", VehicleType.car),
    ("gaz", "GAZ", "Russia", VehicleType.car),
    ("kamaz", "KamAZ", "Russia", VehicleType.truck),
    ("ural", "Ural", "Russia", VehicleType.truck),
    ("maz", "MAZ", "Belarus", VehicleType.truck),
    # Trucks / special
    ("man", "MAN", "Germany", VehicleType.truck),
    ("scania", "Scania", "Sweden", VehicleType.truck),
    ("volvo-trucks", "Volvo Trucks", "Sweden", VehicleType.truck),
    ("caterpillar", "Caterpillar", "USA", VehicleType.special),
    ("jcb", "JCB", "UK", VehicleType.special),
    ("komatsu", "Komatsu", "Japan", VehicleType.special),
]

MODELS: dict[str, list[tuple[str, str]]] = {
    "toyota": [
        ("camry", "Camry"),
        ("corolla", "Corolla"),
        ("rav4", "RAV4"),
        ("land-cruiser", "Land Cruiser"),
        ("prius", "Prius"),
        ("highlander", "Highlander"),
    ],
    "honda": [("accord", "Accord"), ("civic", "Civic"), ("cr-v", "CR-V"), ("pilot", "Pilot")],
    "nissan": [("x-trail", "X-Trail"), ("qashqai", "Qashqai"), ("almera", "Almera"), ("patrol", "Patrol")],
    "mercedes-benz": [
        ("e-class", "E-Class"),
        ("c-class", "C-Class"),
        ("s-class", "S-Class"),
        ("gle", "GLE"),
        ("g-class", "G-Class"),
    ],
    "bmw": [
        ("3-series", "3 Series"),
        ("5-series", "5 Series"),
        ("x5", "X5"),
        ("x3", "X3"),
        ("x7", "X7"),
    ],
    "byd": [
        ("han", "Han"),
        ("tang", "Tang"),
        ("seal", "Seal"),
        ("atto-3", "Atto 3"),
        ("song-plus", "Song Plus"),
    ],
    "li-auto": [("l9", "L9"), ("l7", "L7"), ("l6", "L6"), ("one", "One")],
    "lixiang": [("l9", "L9"), ("l7", "L7"), ("mega", "Mega")],
    "hyundai": [
        ("solaris", "Solaris"),
        ("tucson", "Tucson"),
        ("creta", "Creta"),
        ("sonata", "Sonata"),
        ("elantra", "Elantra"),
    ],
    "kia": [("rio", "Rio"), ("sportage", "Sportage"), ("sorento", "Sorento"), ("k5", "K5"), ("cerato", "Cerato")],
    "lada": [("vesta", "Vesta"), ("granta", "Granta"), ("niva", "Niva"), ("largus", "Largus"), ("xray", "XRAY")],
    "kamaz": [("5490", "5490"), ("6520", "6520"), ("43118", "43118")],
    "tesla": [("model-3", "Model 3"), ("model-y", "Model Y"), ("model-s", "Model S"), ("model-x", "Model X")],
    "lexus": [
        ("lx570", "LX 570"),
        ("lx600", "LX 600"),
        ("rx350", "RX 350"),
        ("es350", "ES 350"),
        ("nx350", "NX 350"),
    ],
    "haval": [("f7", "F7"), ("h6", "H6"), ("jolion", "Jolion"), ("dargo", "Dargo")],
    "changan": [("cs55", "CS55"), ("cs75", "CS75"), ("uni-k", "UNI-K"), ("alsvin", "Alsvin")],
    "chery": [("tiggo-4", "Tiggo 4"), ("tiggo-7", "Tiggo 7"), ("tiggo-8", "Tiggo 8"), ("arrizo-6", "Arrizo 6")],
    "geely": [("coolray", "Coolray"), ("atlas", "Atlas"), ("monjaro", "Monjaro"), ("emgrand", "Emgrand")],
    "jetour": [("x70", "X70"), ("x90", "X90"), ("dashing", "Dashing"), ("t2", "T2")],
    "tank": [("300", "300"), ("500", "500"), ("700", "700")],
    "omoda": [("c5", "C5"), ("s5", "S5")],
    "exeed": [("lx", "LX"), ("txl", "TXL"), ("vx", "VX")],
    "volkswagen": [("polo", "Polo"), ("tiguan", "Tiguan"), ("passat", "Passat"), ("golf", "Golf")],
    "audi": [("a4", "A4"), ("a6", "A6"), ("q5", "Q5"), ("q7", "Q7")],
    "ford": [("focus", "Focus"), ("explorer", "Explorer"), ("ranger", "Ranger"), ("fusion", "Fusion")],
    "chevrolet": [("cruze", "Cruze"), ("malibu", "Malibu"), ("tahoe", "Tahoe"), ("captiva", "Captiva")],
}

BRAND_ALIASES: list[tuple[str, str, VehicleAliasTarget]] = [
    # Mercedes
    ("мерс", "mercedes-benz", VehicleAliasTarget.brand),
    ("мерседес", "mercedes-benz", VehicleAliasTarget.brand),
    ("mercedes", "mercedes-benz", VehicleAliasTarget.brand),
    # Toyota
    ("тойота", "toyota", VehicleAliasTarget.brand),
    ("toyota", "toyota", VehicleAliasTarget.brand),
    # Chinese
    ("бид", "byd", VehicleAliasTarget.brand),
    ("биайди", "byd", VehicleAliasTarget.brand),
    ("byd", "byd", VehicleAliasTarget.brand),
    ("ли авто", "li-auto", VehicleAliasTarget.brand),
    ("lixiang", "lixiang", VehicleAliasTarget.brand),
    ("лисян", "lixiang", VehicleAliasTarget.brand),
    ("хавал", "haval", VehicleAliasTarget.brand),
    ("haval", "haval", VehicleAliasTarget.brand),
    ("чанган", "changan", VehicleAliasTarget.brand),
    ("changan", "changan", VehicleAliasTarget.brand),
    ("чери", "chery", VehicleAliasTarget.brand),
    ("chery", "chery", VehicleAliasTarget.brand),
    ("джили", "geely", VehicleAliasTarget.brand),
    ("geely", "geely", VehicleAliasTarget.brand),
    ("джетур", "jetour", VehicleAliasTarget.brand),
    ("jetour", "jetour", VehicleAliasTarget.brand),
    ("танк", "tank", VehicleAliasTarget.brand),
    ("tank", "tank", VehicleAliasTarget.brand),
    ("омода", "omoda", VehicleAliasTarget.brand),
    ("omoda", "omoda", VehicleAliasTarget.brand),
    ("эксид", "exeed", VehicleAliasTarget.brand),
    ("exeed", "exeed", VehicleAliasTarget.brand),
    # Lexus
    ("лексус", "lexus", VehicleAliasTarget.brand),
    ("lexus", "lexus", VehicleAliasTarget.brand),
    # Other popular
    ("бмв", "bmw", VehicleAliasTarget.brand),
    ("bmw", "bmw", VehicleAliasTarget.brand),
    ("лада", "lada", VehicleAliasTarget.brand),
    ("lada", "lada", VehicleAliasTarget.brand),
    ("камаз", "kamaz", VehicleAliasTarget.brand),
    ("kamaz", "kamaz", VehicleAliasTarget.brand),
    ("хонда", "honda", VehicleAliasTarget.brand),
    ("honda", "honda", VehicleAliasTarget.brand),
    ("хёндай", "hyundai", VehicleAliasTarget.brand),
    ("хендай", "hyundai", VehicleAliasTarget.brand),
    ("hyundai", "hyundai", VehicleAliasTarget.brand),
    ("кия", "kia", VehicleAliasTarget.brand),
    ("kia", "kia", VehicleAliasTarget.brand),
    ("форд", "ford", VehicleAliasTarget.brand),
    ("ford", "ford", VehicleAliasTarget.brand),
    ("тесла", "tesla", VehicleAliasTarget.brand),
    ("tesla", "tesla", VehicleAliasTarget.brand),
    ("ниссан", "nissan", VehicleAliasTarget.brand),
    ("nissan", "nissan", VehicleAliasTarget.brand),
    ("ауди", "audi", VehicleAliasTarget.brand),
    ("audi", "audi", VehicleAliasTarget.brand),
    ("фольксваген", "volkswagen", VehicleAliasTarget.brand),
    ("volkswagen", "volkswagen", VehicleAliasTarget.brand),
    ("vw", "volkswagen", VehicleAliasTarget.brand),
]

MODEL_ALIASES: list[tuple[str, str, str]] = [
    # Toyota Camry
    ("камри", "toyota", "camry"),
    ("camry", "toyota", "camry"),
    ("камри 70", "toyota", "camry"),
    ("camry 70", "toyota", "camry"),
    ("семидесятка", "toyota", "camry"),
    ("королла", "toyota", "corolla"),
    ("corolla", "toyota", "corolla"),
    ("рав4", "toyota", "rav4"),
    ("rav4", "toyota", "rav4"),
    ("приус", "toyota", "prius"),
    # Mercedes
    ("мерс ешка", "mercedes-benz", "e-class"),
    ("ешка", "mercedes-benz", "e-class"),
    ("e-class", "mercedes-benz", "e-class"),
    ("цешка", "mercedes-benz", "c-class"),
    ("c-class", "mercedes-benz", "c-class"),
    ("гелендваген", "mercedes-benz", "g-class"),
    ("гелик", "mercedes-benz", "g-class"),
    # BMW
    ("икс5", "bmw", "x5"),
    ("x5", "bmw", "x5"),
    ("икс3", "bmw", "x3"),
    ("x3", "bmw", "x3"),
    # Hyundai/Kia
    ("солярка", "hyundai", "solaris"),
    ("солярис", "hyundai", "solaris"),
    ("соренто", "kia", "sorento"),
    ("спортейдж", "kia", "sportage"),
    # Lada
    ("веста", "lada", "vesta"),
    ("гранта", "lada", "granta"),
    ("нива", "lada", "niva"),
    # Lexus LX
    ("лх570", "lexus", "lx570"),
    ("lx 570", "lexus", "lx570"),
    ("LX570", "lexus", "lx570"),
    ("лексус 570", "lexus", "lx570"),
    ("лх 570", "lexus", "lx570"),
    ("лх600", "lexus", "lx600"),
    ("lx600", "lexus", "lx600"),
    # BYD
    ("бид хан", "byd", "han"),
    ("byd han", "byd", "han"),
    ("атто 3", "byd", "atto-3"),
    # Li Auto / Lixiang
    ("l9", "li-auto", "l9"),
    ("l7", "li-auto", "l7"),
    ("l9", "lixiang", "l9"),
    # Chinese SUVs
    ("х6 haval", "haval", "h6"),
    ("джолион", "haval", "jolion"),
    ("тигго 7", "chery", "tiggo-7"),
    ("кулрей", "geely", "coolray"),
    ("монжаро", "geely", "monjaro"),
    ("танк 300", "tank", "300"),
    ("танк 500", "tank", "500"),
    # Tesla
    ("модель 3", "tesla", "model-3"),
    ("model 3", "tesla", "model-3"),
    ("модель y", "tesla", "model-y"),
]


def vehicle_seed_counts() -> dict[str, int]:
    return {
        "brands": len(BRANDS),
        "model_definitions": sum(len(v) for v in MODELS.values()),
        "brand_aliases": len(BRAND_ALIASES),
        "model_aliases": len(MODEL_ALIASES),
    }
